package com.armada.account.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import com.armada.account.model.entity.AccountLoginStateCode;
import com.armada.account.model.entity.AccountState;
import com.armada.account.model.entity.AccountStateCode;
import com.armada.boot.config.MyBatisConfig;
import com.armada.shared.tenant.TenantContext;
import com.armada.testsupport.CreatorDeletionH2Schema;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean;
import java.util.List;
import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.test.context.TestExecutionListeners;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;

/** 使用生产租户插件和真实 Mapper 验证连续离线起点的全部登录态写入口。 */
@SpringJUnitConfig(AccountOfflineSinceMapperH2Test.TestConfig.class)
@TestExecutionListeners(listeners = DependencyInjectionTestExecutionListener.class, inheritListeners = false)
class AccountOfflineSinceMapperH2Test {

    private static final long ACCOUNT_ID = 101L;
    private static final long OTHER_ACCOUNT_ID = 201L;

    @Autowired private DataSource dataSource;
    @Autowired private AccountStateMapper states;
    @Autowired private AccountCreatorDeletionMapper deletions;
    @Autowired private PlatformTransactionManager transactionManager;
    private JdbcTemplate jdbc;
    private TransactionTemplate transactions;

    @BeforeEach
    void setUp() {
        jdbc = new JdbcTemplate(dataSource);
        transactions = new TransactionTemplate(transactionManager);
        jdbc.execute("DROP ALL OBJECTS");
        jdbc.execute(CreatorDeletionH2Schema.DDL);
        jdbc.execute("""
                CREATE TABLE account (
                  id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, ws_phone VARCHAR(32),
                  deleted_at BIGINT, creator_deletion_identity_phone VARCHAR(32)
                )
                """);
        jdbc.execute("""
                CREATE TABLE account_state (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL, account_id BIGINT NOT NULL,
                  account_state TINYINT, login_state TINYINT, desired_login_state TINYINT,
                  offline_since BIGINT, last_state_sync_time BIGINT, state_source VARCHAR(64),
                  invalidated_at BIGINT, created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL,
                  UNIQUE (tenant_id, account_id)
                )
                """);
        jdbc.update("INSERT INTO account(id, tenant_id) VALUES (?, 1), (?, 2)", ACCOUNT_ID, OTHER_ACCOUNT_ID);
        jdbc.update("""
                INSERT INTO account_state(tenant_id, account_id, account_state, login_state,
                  last_state_sync_time, state_source, created_at, updated_at)
                VALUES (1, ?, 2, 1, 1000, 'INITIAL', 1000, 1000),
                       (2, ?, 2, 1, 1000, 'INITIAL', 1000, 1000)
                """, ACCOUNT_ID, OTHER_ACCOUNT_ID);
        TenantContext.set(1L);
    }

    @AfterEach
    void clearTenant() {
        TenantContext.clear();
    }

    @ParameterizedTest
    @EnumSource(StateWrite.class)
    void onlineToOfflineRecordsEventTime(StateWrite path) {
        transactions.executeWithoutResult(status -> assertThat(write(path,
                update(ACCOUNT_ID, AccountLoginStateCode.OFFLINE, 2_000L))).isOne());

        assertThat(offlineSince(ACCOUNT_ID)).isEqualTo(2_000L);
        assertThat(loginState(ACCOUNT_ID)).isEqualTo(AccountLoginStateCode.OFFLINE);
    }

    @ParameterizedTest
    @EnumSource(StateWrite.class)
    void repeatedOfflineAndReconnectingKeepTheOriginalStart(StateWrite path) {
        seedOffline(ACCOUNT_ID, 1_500L);
        transactions.executeWithoutResult(status -> {
            assertThat(write(path, update(ACCOUNT_ID, AccountLoginStateCode.OFFLINE, 2_000L))).isOne();
            assertThat(write(path, update(ACCOUNT_ID, AccountLoginStateCode.PENDING_ONLINE, 3_000L))).isOne();
        });

        assertThat(offlineSince(ACCOUNT_ID)).isEqualTo(1_500L);
        assertThat(jdbc.queryForObject("SELECT last_state_sync_time FROM account_state WHERE account_id = ?",
                Long.class, ACCOUNT_ID)).isEqualTo(3_000L);
    }

    @ParameterizedTest
    @EnumSource(StateWrite.class)
    void onlineClearsTheStartAndTheNextDisconnectBeginsANewPeriod(StateWrite path) {
        seedOffline(ACCOUNT_ID, 1_500L);
        transactions.executeWithoutResult(status ->
                assertThat(write(path, update(ACCOUNT_ID, AccountLoginStateCode.ONLINE, 2_000L))).isOne());
        assertThat(offlineSince(ACCOUNT_ID)).isNull();

        transactions.executeWithoutResult(status ->
                assertThat(write(path, update(ACCOUNT_ID, AccountLoginStateCode.OFFLINE, 3_000L))).isOne());
        assertThat(offlineSince(ACCOUNT_ID)).isEqualTo(3_000L);
    }

    @ParameterizedTest
    @EnumSource(PendingWrite.class)
    void pendingOnlineInitializesAnUnknownOfflineStart(PendingWrite path) {
        seedOffline(ACCOUNT_ID, null);
        transactions.executeWithoutResult(status -> assertThat(pending(path, ACCOUNT_ID, 2_000L)).isOne());

        assertThat(offlineSince(ACCOUNT_ID)).isEqualTo(2_000L);
        assertThat(loginState(ACCOUNT_ID)).isEqualTo(AccountLoginStateCode.PENDING_ONLINE);
    }

    @ParameterizedTest
    @EnumSource(PendingWrite.class)
    void pendingOnlineDoesNotRestartAnExistingOfflinePeriod(PendingWrite path) {
        seedOffline(ACCOUNT_ID, 500L);
        transactions.executeWithoutResult(status -> assertThat(pending(path, ACCOUNT_ID, 2_000L)).isOne());

        assertThat(offlineSince(ACCOUNT_ID)).isEqualTo(500L);
        assertThat(loginState(ACCOUNT_ID)).isEqualTo(AccountLoginStateCode.PENDING_ONLINE);
    }

    @ParameterizedTest
    @EnumSource(StateWrite.class)
    void stateEventsCannotWriteAnotherTenantsOfflineStart(StateWrite path) {
        transactions.executeWithoutResult(status -> assertThat(write(path,
                update(OTHER_ACCOUNT_ID, AccountLoginStateCode.OFFLINE, 2_000L))).isZero());

        assertThat(offlineSince(OTHER_ACCOUNT_ID)).isNull();
        assertThat(loginState(OTHER_ACCOUNT_ID)).isEqualTo(AccountLoginStateCode.ONLINE);
        assertThat(states.selectByAccountId(OTHER_ACCOUNT_ID)).isNull();
    }

    @ParameterizedTest
    @EnumSource(PendingWrite.class)
    void pendingClaimsCannotWriteAnotherTenantsOfflineStart(PendingWrite path) {
        seedOffline(OTHER_ACCOUNT_ID, null);
        transactions.executeWithoutResult(status -> assertThat(pending(path, OTHER_ACCOUNT_ID, 2_000L)).isZero());

        assertThat(offlineSince(OTHER_ACCOUNT_ID)).isNull();
        assertThat(loginState(OTHER_ACCOUNT_ID)).isEqualTo(AccountLoginStateCode.OFFLINE);
    }

    @Test
    void creatorDeletionStartsOfflineTimeAndDoesNotRefreshItOnRepeatedCompletion() {
        transactions.executeWithoutResult(status -> assertThat(deletions.markOffline(1L, ACCOUNT_ID, 2_000L)).isOne());
        assertThat(offlineSince(ACCOUNT_ID)).isEqualTo(2_000L);
        transactions.executeWithoutResult(status -> assertThat(deletions.markOffline(1L, ACCOUNT_ID, 3_000L)).isOne());

        assertThat(offlineSince(ACCOUNT_ID)).isEqualTo(2_000L);
        assertThat(loginState(ACCOUNT_ID)).isEqualTo(AccountLoginStateCode.OFFLINE);
        assertThat(jdbc.queryForObject("SELECT account_state FROM account_state WHERE account_id = ?",
                Integer.class, ACCOUNT_ID)).isEqualTo(AccountStateCode.DEREGISTERED);
    }

    @Test
    void creatorDeletionKeepsAnEarlierOfflineStartAndRequiresItsExplicitTenant() {
        seedOffline(ACCOUNT_ID, 500L);
        transactions.executeWithoutResult(status -> {
            assertThat(deletions.markOffline(1L, OTHER_ACCOUNT_ID, 2_000L)).isZero();
            assertThat(deletions.markOffline(1L, ACCOUNT_ID, 2_000L)).isOne();
        });

        assertThat(offlineSince(ACCOUNT_ID)).isEqualTo(500L);
        assertThat(offlineSince(OTHER_ACCOUNT_ID)).isNull();
        assertThat(loginState(OTHER_ACCOUNT_ID)).isEqualTo(AccountLoginStateCode.ONLINE);
    }

    @Test
    void rolledBackStateEventDoesNotPersistItsOfflineStart() {
        transactions.executeWithoutResult(status -> {
            assertThat(states.updateLoginState(update(ACCOUNT_ID, AccountLoginStateCode.OFFLINE, 2_000L))).isOne();
            assertThat(offlineSince(ACCOUNT_ID)).isEqualTo(2_000L);
            status.setRollbackOnly();
        });

        assertThat(offlineSince(ACCOUNT_ID)).isNull();
        assertThat(loginState(ACCOUNT_ID)).isEqualTo(AccountLoginStateCode.ONLINE);
    }

    @Test
    void accountStateMapsThePersistedOfflineStart() {
        seedOffline(ACCOUNT_ID, 500L);
        AccountState state = states.selectByAccountId(ACCOUNT_ID);

        assertThat(state.getOfflineSince()).isEqualTo(500L);
    }

    private int write(StateWrite path, AccountState row) {
        return switch (path) {
            case LOGIN -> states.updateLoginState(row);
            case LOGIN_AND_LIFECYCLE -> states.updateLoginAndAccountState(row);
            case LIFECYCLE -> states.updateLifecycleState(row);
        };
    }

    private int pending(PendingWrite path, long accountId, long now) {
        return switch (path) {
            case MARK -> states.markPendingOnline(List.of(accountId), now);
            case CLAIM -> states.claimPendingOnline(List.of(accountId), now);
            case PROXY_RECOVERY -> states.claimProxyFailedReonline(accountId, 1_000L, now);
        };
    }

    private static AccountState update(long accountId, int loginState, long occurredAt) {
        AccountState row = new AccountState();
        row.setAccountId(accountId);
        row.setAccountState(AccountStateCode.NORMAL);
        row.setLoginState(loginState);
        row.setLastStateSyncTime(occurredAt);
        row.setStateSource("OFFLINE_SINCE_TEST");
        row.setUpdatedAt(occurredAt + 50L);
        return row;
    }

    private void seedOffline(long accountId, Long since) {
        jdbc.update("UPDATE account_state SET login_state = 2, offline_since = ?, state_source = 'PROXY_FAILED' "
                + "WHERE account_id = ?", since, accountId);
    }

    private Long offlineSince(long accountId) {
        return jdbc.queryForObject("SELECT offline_since FROM account_state WHERE account_id = ?", Long.class, accountId);
    }

    private Integer loginState(long accountId) {
        return jdbc.queryForObject("SELECT login_state FROM account_state WHERE account_id = ?", Integer.class, accountId);
    }

    private enum StateWrite { LOGIN, LOGIN_AND_LIFECYCLE, LIFECYCLE }

    private enum PendingWrite { MARK, CLAIM, PROXY_RECOVERY }

    @Configuration(proxyBeanMethods = false)
    @EnableTransactionManagement
    @Import(MyBatisConfig.class)
    static class TestConfig {

        @Bean
        DataSource dataSource() {
            JdbcDataSource source = new JdbcDataSource();
            source.setURL("jdbc:h2:mem:account_offline_since_mapper;MODE=MySQL;"
                    + "DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
            source.setUser("sa");
            source.setPassword("");
            return source;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(DataSource source, MybatisPlusInterceptor interceptor) throws Exception {
            MybatisConfiguration configuration = new MybatisConfiguration();
            configuration.setMapUnderscoreToCamelCase(true);
            MybatisSqlSessionFactoryBean factory = new MybatisSqlSessionFactoryBean();
            factory.setDataSource(source);
            factory.setConfiguration(configuration);
            factory.setPlugins(interceptor);
            factory.setMapperLocations(new ClassPathResource("mapper/account/AccountStateMapper.xml"),
                    new ClassPathResource("mapper/account/AccountCreatorDeletionMapper.xml"));
            return factory.getObject();
        }

        @Bean
        SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory factory) {
            return new SqlSessionTemplate(factory);
        }

        @Bean
        AccountStateMapper stateMapper(SqlSessionTemplate sessions) {
            return sessions.getMapper(AccountStateMapper.class);
        }

        @Bean
        AccountCreatorDeletionMapper deletionMapper(SqlSessionTemplate sessions) {
            return sessions.getMapper(AccountCreatorDeletionMapper.class);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource source) {
            return new DataSourceTransactionManager(source);
        }
    }
}
