package com.armada.group.normalcreation.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import com.armada.boot.config.MyBatisConfig;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.ItemIdentity;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.ItemInsert;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.MemberInsert;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.MemberReplacement;
import com.armada.shared.tenant.TenantContext;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;
import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.test.context.TestExecutionListeners;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

/** 新建普群阶段租约 fencing 与有限重试的真实 Mapper XML 回归测试。 */
@SpringJUnitConfig(NormalGroupCreationMapperH2Test.TestConfig.class)
@TestExecutionListeners(
        listeners = DependencyInjectionTestExecutionListener.class,
        inheritListeners = false)
class NormalGroupCreationMapperH2Test {

    @Autowired private DataSource dataSource;
    @Autowired private NormalGroupCreationMapper mapper;
    @Autowired private PlatformTransactionManager transactionManager;

    @BeforeEach
    void setUp() throws SQLException {
        TenantContext.set(7L);
        execute("DROP ALL OBJECTS");
        execute("""
                CREATE TABLE normal_group_creation_admission_lock (
                  tenant_id BIGINT PRIMARY KEY,
                  created_at BIGINT NOT NULL
                )
                """);
        execute("""
                CREATE TABLE normal_group_creation_item (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  task_id BIGINT NOT NULL,
                  item_no INT NOT NULL DEFAULT 1,
                  group_subject VARCHAR(128) NOT NULL DEFAULT '群',
                  creator_account_id BIGINT NOT NULL DEFAULT 1,
                  creator_protocol_account_id VARCHAR(128) NOT NULL DEFAULT 'acc_1',
                  creator_protocol_backend VARCHAR(16) NOT NULL DEFAULT 'WEB',
                  creator_ws_phone VARCHAR(32) NOT NULL DEFAULT '10001',
                  group_jid VARCHAR(128),
                  create_partial TINYINT NOT NULL DEFAULT 0,
                  status VARCHAR(24) NOT NULL,
                  current_step VARCHAR(32) NOT NULL,
                  dispatch_stage VARCHAR(24) NOT NULL,
                  dispatch_status VARCHAR(16) NOT NULL,
                  next_dispatch_at BIGINT NOT NULL,
                  processing_started_at BIGINT,
                  prepare_attempt_count INT NOT NULL DEFAULT 0,
                  create_attempt_count INT NOT NULL DEFAULT 0,
                  post_attempt_count INT NOT NULL DEFAULT 0,
                  create_command_id VARCHAR(64),
                  settings_command_id VARCHAR(64),
                  leave_command_id VARCHAR(64),
                  contact_prepare_failed TINYINT NOT NULL DEFAULT 0,
                  settings_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
                  creator_leave_status VARCHAR(16) NOT NULL DEFAULT 'SKIPPED',
                  last_event_id VARCHAR(64),
                  last_error_code VARCHAR(64),
                  last_error_message VARCHAR(512),
                  created_at BIGINT NOT NULL DEFAULT 0,
                  updated_at BIGINT NOT NULL,
                  deleted_at BIGINT
                )
                """);
        execute("""
                CREATE TABLE normal_group_creation_item_member (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  task_id BIGINT NOT NULL,
                  item_id BIGINT NOT NULL,
                  member_order INT NOT NULL,
                  member_account_id BIGINT NOT NULL,
                  member_protocol_account_id VARCHAR(128) NOT NULL,
                  member_protocol_backend VARCHAR(16) NOT NULL,
                  member_ws_phone VARCHAR(32) NOT NULL,
                  creator_saved_member_status VARCHAR(16) NOT NULL,
                  member_saved_creator_status VARCHAR(16) NOT NULL,
                  creator_save_command_id VARCHAR(64),
                  member_save_command_id VARCHAR(64),
                  creator_save_error_code VARCHAR(64),
                  creator_save_error_message VARCHAR(512),
                  member_save_error_code VARCHAR(64),
                  member_save_error_message VARCHAR(512),
                  participant_status VARCHAR(32) NOT NULL,
                  participant_raw_status VARCHAR(64),
                  last_error_code VARCHAR(64),
                  last_error_message VARCHAR(512),
                  created_at BIGINT NOT NULL,
                  updated_at BIGINT NOT NULL,
                  UNIQUE (tenant_id, item_id, member_account_id)
                )
                """);
        execute("""
                CREATE TABLE normal_group_creation_task (
                  id BIGINT PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  idempotency_key VARCHAR(64),
                  member_account_group_id BIGINT,
                  total_count INT NOT NULL,
                  status VARCHAR(24) NOT NULL,
                  deleted_at BIGINT,
                  UNIQUE (tenant_id, idempotency_key)
                )
                """);
    }

    @AfterEach
    void tearDown() {
        TenantContext.clear();
    }

    @Test
    void protocolFlowAdvancesAfterBothContactDirectionsSettleAndMatchingCommandIds() throws SQLException {
        insertItem(5L, "PREPARING_CONTACTS", "SENT", "RUNNING", null, 1, 0, 0);
        execute("UPDATE normal_group_creation_item SET group_jid = NULL WHERE id = 5");
        execute("""
                INSERT INTO normal_group_creation_item_member (
                  id, tenant_id, task_id, item_id, member_order, member_account_id,
                  member_protocol_account_id, member_protocol_backend, member_ws_phone,
                  creator_saved_member_status, member_saved_creator_status,
                  creator_save_command_id, member_save_command_id,
                  participant_status, created_at, updated_at
                ) VALUES (
                  51, 7, 99, 5, 1, 21, 'acc_21', 'ANDROID', '10021',
                  'SUCCESS', 'PENDING', 'cmd-contact-creator', 'cmd-contact-member',
                  'PENDING', 100, 100
                )
                """);

        assertThat(mapper.countPendingContactDirections(5L)).isEqualTo(1);
        assertThat(mapper.startGroupCreate(5L, "cmd-create", 200L)).isZero();
        assertThat(mapper.applyContactResult(
                51L, "MEMBER_SAVE_CREATOR", "wrong-command", "SUCCESS",
                null, null, 210L)).isZero();
        assertThat(mapper.applyContactResult(
                51L, "MEMBER_SAVE_CREATOR", "cmd-contact-member", "SUCCESS",
                null, null, 220L)).isEqualTo(1);
        assertThat(mapper.countPendingContactDirections(5L)).isZero();
        assertThat(mapper.startGroupCreate(5L, "cmd-create", 230L)).isEqualTo(1);

        assertThat(mapper.startGroupSettings(
                5L, "wrong-command", "cmd-settings", "1203-new@g.us",
                "ABCDEFGHI3-new", 240L)).isZero();
        assertThat(mapper.startGroupSettings(
                5L, "cmd-create", "cmd-settings", "1203-new@g.us",
                "ABCDEFGHI3-new", 250L)).isEqualTo(1);
        assertThat(mapper.startGroupLeave(
                5L, "wrong-command", "cmd-leave", 260L)).isZero();
        assertThat(mapper.startGroupLeave(
                5L, "cmd-settings", "cmd-leave", 270L)).isEqualTo(1);
        assertThat(mapper.completeProtocolFlow(
                5L, "LEAVING_GROUP", "wrong-command", "SUCCESS", "evt-wrong", 280L)).isZero();
        assertThat(mapper.completeProtocolFlow(
                5L, "LEAVING_GROUP", "cmd-leave", "SUCCESS", "evt-done", 290L)).isEqualTo(1);

        assertThat(value(5L, "status")).isEqualTo("CREATED");
        assertThat(value(5L, "current_step")).isEqualTo("DONE");
        assertThat(value(5L, "group_jid")).isEqualTo("1203-new@g.us");
        assertThat(value(5L, "group_subject")).isEqualTo("ABCDEFGHI3-new");
    }

    @Test
    void failedOrUnknownContactDirectionsNoLongerBlockGroupCreate() throws SQLException {
        insertItem(10L, "PREPARING_CONTACTS", "SENT", "RUNNING", null, 1, 0, 0);
        execute("""
                INSERT INTO normal_group_creation_item_member (
                  id, tenant_id, task_id, item_id, member_order, member_account_id,
                  member_protocol_account_id, member_protocol_backend, member_ws_phone,
                  creator_saved_member_status, member_saved_creator_status,
                  creator_save_command_id, member_save_command_id,
                  participant_status, created_at, updated_at
                ) VALUES (
                  101, 7, 99, 10, 1, 21, 'acc_21', 'ANDROID', '10021',
                  'FAILED', 'PENDING', 'cmd-creator-1', 'cmd-member-1',
                  'PENDING', 100, 100
                ), (
                  102, 7, 99, 10, 2, 22, 'acc_22', 'WEB', '10022',
                  'UNKNOWN', 'SUCCESS', 'cmd-creator-2', 'cmd-member-2',
                  'PENDING', 100, 100
                )
                """);

        assertThat(mapper.countPendingContactDirections(10L)).isEqualTo(1);
        assertThat(mapper.startGroupCreate(10L, "cmd-create", 200L)).isZero();
        assertThat(mapper.applyContactResult(
                101L, "MEMBER_SAVE_CREATOR", "cmd-member-1", "FAILED",
                "ACCOUNT_NOT_ONLINE", "成员账号当前不在线", 210L)).isEqualTo(1);

        assertThat(mapper.countPendingContactDirections(10L)).isZero();
        assertThat(mapper.startGroupCreate(10L, "cmd-create", 220L)).isEqualTo(1);
        assertThat(value(10L, "current_step")).isEqualTo("CREATING_GROUP");
        assertThat(value(10L, "create_command_id")).isEqualTo("cmd-create");
        assertThat(value(10L, "contact_prepare_failed")).isEqualTo("1");
    }

    @Test
    void everyDirectionSucceedingLeavesTheContactFailureFlagClear() throws SQLException {
        insertItem(11L, "PREPARING_CONTACTS", "SENT", "RUNNING", null, 1, 0, 0);
        execute("""
                INSERT INTO normal_group_creation_item_member (
                  id, tenant_id, task_id, item_id, member_order, member_account_id,
                  member_protocol_account_id, member_protocol_backend, member_ws_phone,
                  creator_saved_member_status, member_saved_creator_status,
                  creator_save_command_id, member_save_command_id,
                  participant_status, created_at, updated_at
                ) VALUES (
                  111, 7, 99, 11, 1, 21, 'acc_21', 'ANDROID', '10021',
                  'SUCCESS', 'SUCCESS', 'cmd-creator-1', 'cmd-member-1',
                  'PENDING', 100, 100
                )
                """);

        assertThat(mapper.startGroupCreate(11L, "cmd-create", 200L)).isEqualTo(1);

        assertThat(value(11L, "contact_prepare_failed")).isEqualTo("0");
        assertThat(mapper.selectContactFailures(99L)).isEmpty();
    }

    @Test
    void contactFailureReasonsAreKeptPerDirectionAndNotClearedByTheOtherDirection()
            throws SQLException {
        insertItem(12L, "PREPARING_CONTACTS", "SENT", "RUNNING", null, 1, 0, 0);
        execute("""
                INSERT INTO normal_group_creation_item_member (
                  id, tenant_id, task_id, item_id, member_order, member_account_id,
                  member_protocol_account_id, member_protocol_backend, member_ws_phone,
                  creator_saved_member_status, member_saved_creator_status,
                  creator_save_command_id, member_save_command_id,
                  participant_status, created_at, updated_at
                ) VALUES (
                  121, 7, 99, 12, 1, 21, 'acc_21', 'ANDROID', '10021',
                  'PENDING', 'PENDING', 'cmd-creator-1', 'cmd-member-1',
                  'PENDING', 100, 100
                )
                """);

        assertThat(mapper.applyContactResult(
                121L, "CREATOR_SAVE_MEMBER", "cmd-creator-1", "FAILED",
                "ACCOUNT_NOT_ONLINE", "建群账号当前不在线，请重新上线后重试", 200L)).isEqualTo(1);
        assertThat(mapper.applyContactResult(
                121L, "MEMBER_SAVE_CREATOR", "cmd-member-1", "SUCCESS",
                null, null, 210L)).isEqualTo(1);

        assertThat(memberValue(121L, "creator_save_error_code")).isEqualTo("ACCOUNT_NOT_ONLINE");
        assertThat(memberValue(121L, "creator_save_error_message"))
                .isEqualTo("建群账号当前不在线，请重新上线后重试");
        assertThat(memberValue(121L, "member_save_error_code")).isNull();
        assertThat(mapper.selectContactFailures(99L)).singleElement().satisfies(failure -> {
            assertThat(failure.itemId()).isEqualTo(12L);
            assertThat(failure.memberAccountId()).isEqualTo(21L);
            assertThat(failure.creatorSavedMemberStatus()).isEqualTo("FAILED");
            assertThat(failure.creatorSaveErrorCode()).isEqualTo("ACCOUNT_NOT_ONLINE");
            assertThat(failure.creatorSaveErrorMessage())
                    .isEqualTo("建群账号当前不在线，请重新上线后重试");
            assertThat(failure.memberSavedCreatorStatus()).isEqualTo("SUCCESS");
            assertThat(failure.memberSaveErrorMessage()).isNull();
        });
    }

    @Test
    void retryContactCommandsReplacePendingAndUnknownFencingTokens() throws SQLException {
        insertItem(8L, "PREPARING_CONTACTS", "NONE", "FAILED", null, 1, 0, 0);
        execute("""
                INSERT INTO normal_group_creation_item_member (
                  id, tenant_id, task_id, item_id, member_order, member_account_id,
                  member_protocol_account_id, member_protocol_backend, member_ws_phone,
                  creator_saved_member_status, member_saved_creator_status,
                  creator_save_command_id, member_save_command_id,
                  participant_status, created_at, updated_at
                ) VALUES (
                  81, 7, 99, 8, 1, 21, 'acc_21', 'ANDROID', '10021',
                  'PENDING', 'UNKNOWN', 'cmd-creator-old', 'cmd-member-old',
                  'PENDING', 100, 100
                )
                """);

        assertThat(mapper.bindContactCommand(
                81L, "CREATOR_SAVE_MEMBER", "PENDING", "cmd-creator-retry", 200L))
                .isEqualTo(1);
        assertThat(mapper.bindContactCommand(
                81L, "MEMBER_SAVE_CREATOR", "UNKNOWN", "cmd-member-retry", 210L))
                .isEqualTo(1);
        assertThat(mapper.applyContactResult(
                81L, "CREATOR_SAVE_MEMBER", "cmd-creator-old", "SUCCESS",
                null, null, 220L)).isZero();
        assertThat(mapper.applyContactResult(
                81L, "MEMBER_SAVE_CREATOR", "cmd-member-old", "SUCCESS",
                null, null, 230L)).isZero();
        assertThat(mapper.applyContactResult(
                81L, "CREATOR_SAVE_MEMBER", "cmd-creator-retry", "SUCCESS",
                null, null, 240L)).isEqualTo(1);
        assertThat(mapper.applyContactResult(
                81L, "MEMBER_SAVE_CREATOR", "cmd-member-retry", "SUCCESS",
                null, null, 250L)).isEqualTo(1);

        assertThat(mapper.selectMemberWorks(8L)).singleElement().satisfies(member -> {
            assertThat(member.creatorSavedMemberStatus()).isEqualTo("SUCCESS");
            assertThat(member.memberSavedCreatorStatus()).isEqualTo("SUCCESS");
            assertThat(member.creatorSaveCommandId()).isEqualTo("cmd-creator-retry");
            assertThat(member.memberSaveCommandId()).isEqualTo("cmd-member-retry");
        });
    }

    @Test
    void failedContactRetryCanReplaceUnavailableMemberAndFenceOldResults() throws SQLException {
        execute("""
                INSERT INTO normal_group_creation_task (
                  id, tenant_id, idempotency_key, member_account_group_id,
                  total_count, status, deleted_at
                ) VALUES (99, 7, 'replace-member', 20, 1, 'FAILED', NULL)
                """);
        insertItem(9L, "PREPARING_CONTACTS", "NONE", "FAILED", null, 1, 0, 0);
        execute("""
                INSERT INTO normal_group_creation_item_member (
                  id, tenant_id, task_id, item_id, member_order, member_account_id,
                  member_protocol_account_id, member_protocol_backend, member_ws_phone,
                  creator_saved_member_status, member_saved_creator_status,
                  creator_save_command_id, member_save_command_id,
                  member_save_error_code, member_save_error_message,
                  participant_status, participant_raw_status, created_at, updated_at
                ) VALUES (
                  91, 7, 99, 9, 1, 21, 'acc_21', 'ANDROID', '10021',
                  'SUCCESS', 'FAILED', 'cmd-creator-old', 'cmd-member-old',
                  'ACCOUNT_NOT_ONLINE', '旧账号不在线',
                  'PENDING', 'OFFLINE', 100, 100
                )
                """);

        assertThat(mapper.selectMemberAccountGroupId(99L)).isEqualTo(20L);
        assertThat(mapper.replaceMember(new MemberReplacement(
                91L, 9L, 999L, 22L, "acc_22", "ANDROID", "10022", 190L)))
                .isZero();
        assertThat(mapper.replaceMember(new MemberReplacement(
                91L, 9L, 21L, 22L, "acc_22", "ANDROID", "10022", 200L)))
                .isEqualTo(1);

        assertThat(mapper.selectMemberWorks(9L)).singleElement().satisfies(member -> {
            assertThat(member.memberAccountId()).isEqualTo(22L);
            assertThat(member.memberProtocolAccountId()).isEqualTo("acc_22");
            assertThat(member.memberProtocolBackend()).isEqualTo("ANDROID");
            assertThat(member.memberWsPhone()).isEqualTo("10022");
            assertThat(member.creatorSavedMemberStatus()).isEqualTo("PENDING");
            assertThat(member.memberSavedCreatorStatus()).isEqualTo("PENDING");
            assertThat(member.creatorSaveCommandId()).isNull();
            assertThat(member.memberSaveCommandId()).isNull();
        });
        assertThat(memberValue(91L, "participant_raw_status")).isNull();
        assertThat(memberValue(91L, "creator_save_error_code")).isNull();
        assertThat(memberValue(91L, "creator_save_error_message")).isNull();
        assertThat(memberValue(91L, "member_save_error_code")).isNull();
        assertThat(memberValue(91L, "member_save_error_message")).isNull();
        assertThat(mapper.applyContactResult(
                91L, "CREATOR_SAVE_MEMBER", "cmd-creator-old", "SUCCESS",
                null, null, 210L)).isZero();
        assertThat(mapper.applyContactResult(
                91L, "MEMBER_SAVE_CREATOR", "cmd-member-old", "SUCCESS",
                null, null, 220L)).isZero();
    }

    @Test
    void failedCreateWithReturnedGroupJidConvergesToPartialAndCannotBeCompleted() throws SQLException {
        insertItem(6L, "CREATING_GROUP", "SENT", "RUNNING", null, 0, 1, 0);
        execute("""
                UPDATE normal_group_creation_item
                SET group_jid = NULL, create_command_id = 'cmd-create'
                WHERE id = 6
                """);

        assertThat(mapper.failProtocolAction(
                6L, "CREATING_GROUP", "wrong-command", "CREATED_PARTIAL",
                "PARTIAL", "部分成员未确认", "1203-partial@g.us", "evt-wrong", 200L)).isZero();
        assertThat(mapper.failProtocolAction(
                6L, "CREATING_GROUP", "cmd-create", "CREATED_PARTIAL",
                "PARTIAL", "部分成员未确认", "1203-partial@g.us", "evt-partial", 210L)).isEqualTo(1);

        assertThat(value(6L, "status")).isEqualTo("CREATED_PARTIAL");
        assertThat(value(6L, "group_jid")).isEqualTo("1203-partial@g.us");
        assertThat(value(6L, "create_partial")).isEqualTo("1");
        assertThat(mapper.completeProtocolFlow(
                6L, "CREATING_GROUP", "cmd-create", "SUCCESS", "evt-done", 220L)).isZero();
    }

    @Test
    void retryLeaveReplacesCommandAndResetsFailedPostState() throws SQLException {
        insertItem(7L, "LEAVING_GROUP", "NONE", "FAILED", "evt-failed", 0, 1, 2);
        execute("""
                UPDATE normal_group_creation_item
                SET leave_command_id = 'cmd-leave-old', settings_status = 'SUCCESS',
                    creator_leave_status = 'FAILED'
                WHERE id = 7
                """);

        assertThat(mapper.retryProtocolAction(
                7L, "LEAVING_GROUP", "cmd-leave-new", 300L)).isEqualTo(1);

        assertThat(value(7L, "status")).isEqualTo("RUNNING");
        assertThat(value(7L, "dispatch_stage")).isEqualTo("GROUP_LEAVE");
        assertThat(value(7L, "leave_command_id")).isEqualTo("cmd-leave-new");
        assertThat(value(7L, "creator_leave_status")).isEqualTo("PENDING");
        assertThat(value(7L, "post_attempt_count")).isEqualTo("3");
    }

    @Test
    void idempotencyLookupReturnsOnlyTheExplicitTenantTask() throws SQLException {
        execute("""
                INSERT INTO normal_group_creation_task
                  (id, tenant_id, idempotency_key, total_count, status, deleted_at)
                VALUES
                  (701, 7, 'shared-idempotency-key', 1, 'PENDING', NULL),
                  (801, 8, 'shared-idempotency-key', 1, 'PENDING', NULL)
                """);
        TenantContext.set(8L);

        assertThat(mapper.selectTaskIdByIdempotencyKey(7L, "shared-idempotency-key"))
                .isEqualTo(701L);
    }

    @Test
    void lockingIdempotencyLookupReturnsOnlyTheExplicitTenantTask() throws SQLException {
        execute("""
                INSERT INTO normal_group_creation_task
                  (id, tenant_id, idempotency_key, total_count, status, deleted_at)
                VALUES
                  (702, 7, 'shared-lock-key', 1, 'PENDING', NULL),
                  (802, 8, 'shared-lock-key', 1, 'PENDING', NULL)
                """);
        TenantContext.set(8L);
        TransactionTemplate transactions = new TransactionTemplate(transactionManager);

        Long taskId = transactions.execute(status ->
                mapper.selectTaskIdByIdempotencyKeyForUpdate(7L, "shared-lock-key"));

        assertThat(taskId).isEqualTo(702L);
    }

    @Test
    void activeLoadCurrentReadOnlyReturnsCurrentTenantAndNonTerminalTasks() throws SQLException {
        execute("""
                INSERT INTO normal_group_creation_task
                  (id, tenant_id, total_count, status, deleted_at)
                VALUES
                  (11, 7, 10, 'PENDING', NULL),
                  (12, 7, 20, 'RUNNING', NULL),
                  (13, 7, 100, 'SUCCESS', NULL),
                  (14, 7, 200, 'PENDING', 123),
                  (15, 8, 300, 'PENDING', NULL)
                """);

        List<Integer> groupCounts = mapper.selectActiveGroupCountsForUpdate(7L);

        assertThat(groupCounts).containsExactly(10, 20);
    }

    @Test
    void admissionLockCanBeCreatedAndLockedForCurrentTenant() {
        assertThat(mapper.ensureAdmissionLock(7L, 100L)).isEqualTo(1);
        assertThat(mapper.ensureAdmissionLock(7L, 200L)).isZero();
        assertThat(mapper.lockAdmission(7L)).isEqualTo(7L);
    }

    @Test
    void batchInsertItemsAndMembersUsesCurrentTenantAndSingleIdentityRead() throws SQLException {
        mapper.insertItems(List.of(
                new ItemInsert(99L, 1, "群-1", 11L, "acc_11", "WEB", "10011", 100L),
                new ItemInsert(99L, 2, "群-2", 12L, "acc_12", "ANDROID", "10012", 100L)));

        List<ItemIdentity> identities = mapper.selectItemIdentities(99L);

        assertThat(identities).extracting(ItemIdentity::itemNo).containsExactly(1, 2);
        mapper.insertMembers(List.of(
                new MemberInsert(99L, identities.get(0).id(), 1,
                        21L, "acc_21", "WEB", "10021", 100L),
                new MemberInsert(99L, identities.get(1).id(), 1,
                        22L, "acc_22", "ANDROID", "10022", 100L)));
        assertThat(count("normal_group_creation_item", 7L)).isEqualTo(2);
        assertThat(count("normal_group_creation_item_member", 7L)).isEqualTo(2);
    }

    @Test
    void concurrentCapacityReaderWaitsForPriorTenantTaskCommit() throws Exception {
        execute("""
                INSERT INTO normal_group_creation_task
                  (id, tenant_id, total_count, status, deleted_at)
                VALUES
                  (1, 7, 1, 'PENDING', NULL),
                  (2, 7, 1, 'PENDING', NULL),
                  (3, 7, 1, 'PENDING', NULL),
                  (4, 7, 1, 'PENDING', NULL),
                  (5, 7, 1, 'PENDING', NULL),
                  (6, 7, 1, 'PENDING', NULL),
                  (7, 7, 1, 'PENDING', NULL),
                  (8, 7, 1, 'PENDING', NULL),
                  (9, 7, 1, 'PENDING', NULL),
                  (10, 7, 1, 'PENDING', NULL),
                  (11, 7, 1, 'PENDING', NULL),
                  (12, 7, 1, 'PENDING', NULL),
                  (13, 7, 1, 'PENDING', NULL),
                  (14, 7, 1, 'PENDING', NULL),
                  (15, 7, 1, 'PENDING', NULL),
                  (16, 7, 1, 'PENDING', NULL),
                  (17, 7, 1, 'PENDING', NULL),
                  (18, 7, 1, 'PENDING', NULL),
                  (19, 7, 1, 'PENDING', NULL)
                """);
        CountDownLatch firstLocked = new CountDownLatch(1);
        CountDownLatch releaseFirst = new CountDownLatch(1);
        CountDownLatch secondAttemptingLock = new CountDownLatch(1);
        CountDownLatch secondFinished = new CountDownLatch(1);
        AtomicReference<List<Integer>> secondCurrentCounts = new AtomicReference<>();
        ExecutorService executor = Executors.newFixedThreadPool(2);
        TransactionTemplate transactions = new TransactionTemplate(transactionManager);
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        try {
            mapper.ensureAdmissionLock(7L, 50L);
            Future<?> first = executor.submit(() -> transactions.executeWithoutResult(status -> {
                TenantContext.set(7L);
                try {
                    mapper.ensureAdmissionLock(7L, 100L);
                    mapper.lockAdmission(7L);
                    jdbc.update("""
                            INSERT INTO normal_group_creation_task
                              (id, tenant_id, total_count, status, deleted_at)
                            VALUES (20, 7, 1, 'PENDING', NULL)
                            """);
                    firstLocked.countDown();
                    await(releaseFirst);
                } finally {
                    TenantContext.clear();
                }
            }));
            assertThat(firstLocked.await(2, TimeUnit.SECONDS)).isTrue();
            Future<?> second = executor.submit(() -> {
                try {
                    transactions.executeWithoutResult(status -> {
                        TenantContext.set(7L);
                        try {
                            secondAttemptingLock.countDown();
                            mapper.ensureAdmissionLock(7L, 200L);
                            mapper.lockAdmission(7L);
                            secondCurrentCounts.set(
                                    mapper.selectActiveGroupCountsForUpdate(7L));
                        } finally {
                            TenantContext.clear();
                        }
                    });
                } finally {
                    secondFinished.countDown();
                }
            });

            assertThat(secondAttemptingLock.await(2, TimeUnit.SECONDS)).isTrue();
            assertThat(secondFinished.await(200, TimeUnit.MILLISECONDS)).isFalse();
            releaseFirst.countDown();
            first.get(2, TimeUnit.SECONDS);
            second.get(2, TimeUnit.SECONDS);
            assertThat(secondCurrentCounts.get()).hasSize(20);
        } finally {
            releaseFirst.countDown();
            executor.shutdownNow();
        }
    }

    private static void await(CountDownLatch latch) {
        try {
            if (!latch.await(2, TimeUnit.SECONDS)) {
                throw new IllegalStateException("等待并发测试信号超时");
            }
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("并发测试被中断", ex);
        }
    }

    private void insertItem(
            long id,
            String step,
            String dispatchStatus,
            String status,
            String eventId,
            int prepareAttempts,
            int createAttempts,
            int postAttempts) throws SQLException {
        execute("""
                INSERT INTO normal_group_creation_item (
                  id, tenant_id, task_id, group_jid, status, current_step,
                  dispatch_stage, dispatch_status, next_dispatch_at, processing_started_at,
                  prepare_attempt_count, create_attempt_count, post_attempt_count,
                  last_event_id, updated_at
                ) VALUES (
                  %d, 7, 99, '1203@g.us', '%s', '%s', 'PREPARE', '%s', 100, 100,
                  %d, %d, %d, '%s', 100
                )
                """.formatted(
                id, status, step, dispatchStatus,
                prepareAttempts, createAttempts, postAttempts, eventId));
    }

    private String value(long id, String column) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery(
                     "SELECT " + column + " FROM normal_group_creation_item WHERE id = " + id)) {
            assertThat(result.next()).isTrue();
            return result.getString(1);
        }
    }

    private String memberValue(long id, String column) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery(
                     "SELECT " + column
                             + " FROM normal_group_creation_item_member WHERE id = " + id)) {
            assertThat(result.next()).isTrue();
            return result.getString(1);
        }
    }

    private long count(String table, long tenantId) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery(
                     "SELECT COUNT(*) FROM " + table + " WHERE tenant_id = " + tenantId)) {
            assertThat(result.next()).isTrue();
            return result.getLong(1);
        }
    }

    private void execute(String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    @Configuration(proxyBeanMethods = false)
    @Import(MyBatisConfig.class)
    static class TestConfig {

        @Bean
        DataSource dataSource() {
            JdbcDataSource h2 = new JdbcDataSource();
            h2.setURL("jdbc:h2:mem:normal_group_creation_mapper_test;MODE=MySQL;"
                    + "DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
            h2.setUser("sa");
            h2.setPassword("");
            return h2;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(
                DataSource dataSource,
                MybatisPlusInterceptor interceptor) throws Exception {
            MybatisConfiguration configuration = new MybatisConfiguration();
            configuration.setMapUnderscoreToCamelCase(true);
            MybatisSqlSessionFactoryBean factory = new MybatisSqlSessionFactoryBean();
            factory.setDataSource(dataSource);
            factory.setConfiguration(configuration);
            factory.setPlugins(interceptor);
            factory.setMapperLocations(new ClassPathResource(
                    "mapper/group/normalcreation/NormalGroupCreationMapper.xml"));
            return factory.getObject();
        }

        @Bean
        SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory factory) {
            return new SqlSessionTemplate(factory);
        }

        @Bean
        NormalGroupCreationMapper mapper(SqlSessionTemplate template) {
            return template.getMapper(NormalGroupCreationMapper.class);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }
    }
}
