package com.armada.group.normalcreation.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import com.armada.boot.config.MyBatisConfig;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.ItemIdentity;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.ItemInsert;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.MemberInsert;
import com.armada.shared.tenant.TenantContext;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;
import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.test.context.TestExecutionListeners;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

/** 新建普群阶段租约 fencing 与有限重试的真实 Mapper XML 回归测试。 */
@SpringJUnitConfig(NormalGroupCreationMapperH2Test.TestConfig.class)
@TestExecutionListeners(
        listeners = DependencyInjectionTestExecutionListener.class,
        inheritListeners = false)
class NormalGroupCreationMapperH2Test {

    @Autowired private DataSource dataSource;
    @Autowired private NormalGroupCreationMapper mapper;
    @Autowired private PlatformTransactionManager transactionManager;

    @BeforeEach
    void setUp() throws SQLException {
        TenantContext.set(7L);
        execute("DROP ALL OBJECTS");
        execute("""
                CREATE TABLE normal_group_creation_admission_lock (
                  tenant_id BIGINT PRIMARY KEY,
                  created_at BIGINT NOT NULL
                )
                """);
        execute("""
                CREATE TABLE normal_group_creation_item (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  task_id BIGINT NOT NULL,
                  item_no INT NOT NULL DEFAULT 1,
                  group_subject VARCHAR(128) NOT NULL DEFAULT '群',
                  creator_account_id BIGINT NOT NULL DEFAULT 1,
                  creator_protocol_account_id VARCHAR(128) NOT NULL DEFAULT 'acc_1',
                  creator_protocol_backend VARCHAR(16) NOT NULL DEFAULT 'WEB',
                  creator_ws_phone VARCHAR(32) NOT NULL DEFAULT '10001',
                  group_jid VARCHAR(128),
                  create_partial TINYINT NOT NULL DEFAULT 0,
                  status VARCHAR(24) NOT NULL,
                  current_step VARCHAR(32) NOT NULL,
                  dispatch_stage VARCHAR(24) NOT NULL,
                  dispatch_status VARCHAR(16) NOT NULL,
                  next_dispatch_at BIGINT NOT NULL,
                  processing_started_at BIGINT,
                  prepare_attempt_count INT NOT NULL DEFAULT 0,
                  create_attempt_count INT NOT NULL DEFAULT 0,
                  post_attempt_count INT NOT NULL DEFAULT 0,
                  settings_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
                  creator_leave_status VARCHAR(16) NOT NULL DEFAULT 'SKIPPED',
                  last_event_id VARCHAR(64),
                  last_error_code VARCHAR(64),
                  last_error_message VARCHAR(512),
                  created_at BIGINT NOT NULL DEFAULT 0,
                  updated_at BIGINT NOT NULL,
                  deleted_at BIGINT
                )
                """);
        execute("""
                CREATE TABLE normal_group_creation_item_member (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  task_id BIGINT NOT NULL,
                  item_id BIGINT NOT NULL,
                  member_order INT NOT NULL,
                  member_account_id BIGINT NOT NULL,
                  member_protocol_account_id VARCHAR(128) NOT NULL,
                  member_protocol_backend VARCHAR(16) NOT NULL,
                  member_ws_phone VARCHAR(32) NOT NULL,
                  creator_saved_member_status VARCHAR(16) NOT NULL,
                  member_saved_creator_status VARCHAR(16) NOT NULL,
                  participant_status VARCHAR(32) NOT NULL,
                  created_at BIGINT NOT NULL,
                  updated_at BIGINT NOT NULL
                )
                """);
        execute("""
                CREATE TABLE normal_group_creation_task (
                  id BIGINT PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  total_count INT NOT NULL,
                  status VARCHAR(24) NOT NULL,
                  deleted_at BIGINT
                )
                """);
    }

    @AfterEach
    void tearDown() {
        TenantContext.clear();
    }

    @Test
    void staleEventCannotCompleteOrFailAfterNewLeaseClaimsItem() throws SQLException {
        insertItem(1L, "PREPARING_CONTACTS", "PROCESSING", "RUNNING", "old-event", 1, 0, 0);

        assertThat(mapper.recoverExpiredProcessing(
                1L, "PREPARING_CONTACTS", 100L, 3, 200L))
                .isEqualTo(1);
        assertThat(mapper.claimStage(1L, "PREPARING_CONTACTS", "new-event", "prepare", 300L))
                .isEqualTo(1);

        assertThat(mapper.completePrepare(1L, "old-event", 400L)).isZero();
        assertThat(mapper.failItem(
                1L, "FAILED", "STALE", "旧消费者", "old-event", 400L)).isZero();
        assertThat(mapper.completePrepare(1L, "new-event", 400L)).isEqualTo(1);
    }

    @Test
    void expiredPostProcessingConvergesToPartialInsteadOfReplayingLeave() throws SQLException {
        insertItem(2L, "POST_PROCESSING", "PROCESSING", "RUNNING", "post-event", 0, 0, 1);

        assertThat(mapper.recoverExpiredProcessing(
                2L, "POST_PROCESSING", 100L, 3, 200L))
                .isEqualTo(1);

        assertThat(value(2L, "status")).isEqualTo("CREATED_PARTIAL");
        assertThat(value(2L, "dispatch_status")).isEqualTo("NONE");
    }

    @Test
    void exhaustedCreateRetryConvergesToResultUnknown() throws SQLException {
        insertItem(3L, "CREATING_GROUP", "PROCESSING", "RUNNING", "create-event", 0, 3, 0);

        assertThat(mapper.releaseStageForRetry(
                3L, "CREATING_GROUP", "create-event", 3,
                "TIMEOUT", "协议超时", 500L, 400L)).isEqualTo(1);

        assertThat(value(3L, "status")).isEqualTo("RESULT_UNKNOWN");
        assertThat(value(3L, "dispatch_status")).isEqualTo("NONE");
    }

    @Test
    void exhaustedPrepareLeaseBecomesFailedInsteadOfBeingRepublishedForever() throws SQLException {
        insertItem(4L, "PREPARING_CONTACTS", "PROCESSING", "RUNNING", "prepare-event", 3, 0, 0);

        assertThat(mapper.recoverExpiredProcessing(
                4L, "PREPARING_CONTACTS", 100L, 3, 200L)).isEqualTo(1);

        assertThat(value(4L, "status")).isEqualTo("FAILED");
        assertThat(value(4L, "dispatch_stage")).isEqualTo("NONE");
        assertThat(value(4L, "dispatch_status")).isEqualTo("NONE");
    }

    @Test
    void activeLoadCurrentReadOnlyReturnsCurrentTenantAndNonTerminalTasks() throws SQLException {
        execute("""
                INSERT INTO normal_group_creation_task
                  (id, tenant_id, total_count, status, deleted_at)
                VALUES
                  (11, 7, 10, 'PENDING', NULL),
                  (12, 7, 20, 'RUNNING', NULL),
                  (13, 7, 100, 'SUCCESS', NULL),
                  (14, 7, 200, 'PENDING', 123),
                  (15, 8, 300, 'PENDING', NULL)
                """);

        List<Integer> groupCounts = mapper.selectActiveGroupCountsForUpdate();

        assertThat(groupCounts).containsExactly(10, 20);
    }

    @Test
    void admissionLockCanBeCreatedAndLockedForCurrentTenant() {
        assertThat(mapper.ensureAdmissionLock(7L, 100L)).isEqualTo(1);
        assertThat(mapper.ensureAdmissionLock(7L, 200L)).isZero();
        assertThat(mapper.lockAdmission(7L)).isEqualTo(7L);
    }

    @Test
    void batchInsertItemsAndMembersUsesCurrentTenantAndSingleIdentityRead() throws SQLException {
        mapper.insertItems(List.of(
                new ItemInsert(99L, 1, "群-1", 11L, "acc_11", "WEB", "10011", 100L),
                new ItemInsert(99L, 2, "群-2", 12L, "acc_12", "ANDROID", "10012", 100L)));

        List<ItemIdentity> identities = mapper.selectItemIdentities(99L);

        assertThat(identities).extracting(ItemIdentity::itemNo).containsExactly(1, 2);
        mapper.insertMembers(List.of(
                new MemberInsert(99L, identities.get(0).id(), 1,
                        21L, "acc_21", "WEB", "10021", 100L),
                new MemberInsert(99L, identities.get(1).id(), 1,
                        22L, "acc_22", "ANDROID", "10022", 100L)));
        assertThat(count("normal_group_creation_item", 7L)).isEqualTo(2);
        assertThat(count("normal_group_creation_item_member", 7L)).isEqualTo(2);
    }

    @Test
    void concurrentCapacityReaderWaitsForPriorTenantTaskCommit() throws Exception {
        execute("""
                INSERT INTO normal_group_creation_task
                  (id, tenant_id, total_count, status, deleted_at)
                VALUES
                  (1, 7, 1, 'PENDING', NULL),
                  (2, 7, 1, 'PENDING', NULL),
                  (3, 7, 1, 'PENDING', NULL),
                  (4, 7, 1, 'PENDING', NULL),
                  (5, 7, 1, 'PENDING', NULL),
                  (6, 7, 1, 'PENDING', NULL),
                  (7, 7, 1, 'PENDING', NULL),
                  (8, 7, 1, 'PENDING', NULL),
                  (9, 7, 1, 'PENDING', NULL),
                  (10, 7, 1, 'PENDING', NULL),
                  (11, 7, 1, 'PENDING', NULL),
                  (12, 7, 1, 'PENDING', NULL),
                  (13, 7, 1, 'PENDING', NULL),
                  (14, 7, 1, 'PENDING', NULL),
                  (15, 7, 1, 'PENDING', NULL),
                  (16, 7, 1, 'PENDING', NULL),
                  (17, 7, 1, 'PENDING', NULL),
                  (18, 7, 1, 'PENDING', NULL),
                  (19, 7, 1, 'PENDING', NULL)
                """);
        CountDownLatch firstLocked = new CountDownLatch(1);
        CountDownLatch releaseFirst = new CountDownLatch(1);
        CountDownLatch secondAttemptingLock = new CountDownLatch(1);
        CountDownLatch secondFinished = new CountDownLatch(1);
        AtomicReference<List<Integer>> secondCurrentCounts = new AtomicReference<>();
        ExecutorService executor = Executors.newFixedThreadPool(2);
        TransactionTemplate transactions = new TransactionTemplate(transactionManager);
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        try {
            mapper.ensureAdmissionLock(7L, 50L);
            Future<?> first = executor.submit(() -> transactions.executeWithoutResult(status -> {
                TenantContext.set(7L);
                try {
                    mapper.ensureAdmissionLock(7L, 100L);
                    mapper.lockAdmission(7L);
                    jdbc.update("""
                            INSERT INTO normal_group_creation_task
                              (id, tenant_id, total_count, status, deleted_at)
                            VALUES (20, 7, 1, 'PENDING', NULL)
                            """);
                    firstLocked.countDown();
                    await(releaseFirst);
                } finally {
                    TenantContext.clear();
                }
            }));
            assertThat(firstLocked.await(2, TimeUnit.SECONDS)).isTrue();
            Future<?> second = executor.submit(() -> {
                try {
                    transactions.executeWithoutResult(status -> {
                        TenantContext.set(7L);
                        try {
                            secondAttemptingLock.countDown();
                            mapper.ensureAdmissionLock(7L, 200L);
                            mapper.lockAdmission(7L);
                            secondCurrentCounts.set(
                                    mapper.selectActiveGroupCountsForUpdate());
                        } finally {
                            TenantContext.clear();
                        }
                    });
                } finally {
                    secondFinished.countDown();
                }
            });

            assertThat(secondAttemptingLock.await(2, TimeUnit.SECONDS)).isTrue();
            assertThat(secondFinished.await(200, TimeUnit.MILLISECONDS)).isFalse();
            releaseFirst.countDown();
            first.get(2, TimeUnit.SECONDS);
            second.get(2, TimeUnit.SECONDS);
            assertThat(secondCurrentCounts.get()).hasSize(20);
        } finally {
            releaseFirst.countDown();
            executor.shutdownNow();
        }
    }

    private static void await(CountDownLatch latch) {
        try {
            if (!latch.await(2, TimeUnit.SECONDS)) {
                throw new IllegalStateException("等待并发测试信号超时");
            }
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("并发测试被中断", ex);
        }
    }

    private void insertItem(
            long id,
            String step,
            String dispatchStatus,
            String status,
            String eventId,
            int prepareAttempts,
            int createAttempts,
            int postAttempts) throws SQLException {
        execute("""
                INSERT INTO normal_group_creation_item (
                  id, tenant_id, task_id, group_jid, status, current_step,
                  dispatch_stage, dispatch_status, next_dispatch_at, processing_started_at,
                  prepare_attempt_count, create_attempt_count, post_attempt_count,
                  last_event_id, updated_at
                ) VALUES (
                  %d, 7, 99, '1203@g.us', '%s', '%s', 'PREPARE', '%s', 100, 100,
                  %d, %d, %d, '%s', 100
                )
                """.formatted(
                id, status, step, dispatchStatus,
                prepareAttempts, createAttempts, postAttempts, eventId));
    }

    private String value(long id, String column) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery(
                     "SELECT " + column + " FROM normal_group_creation_item WHERE id = " + id)) {
            assertThat(result.next()).isTrue();
            return result.getString(1);
        }
    }

    private long count(String table, long tenantId) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet result = statement.executeQuery(
                     "SELECT COUNT(*) FROM " + table + " WHERE tenant_id = " + tenantId)) {
            assertThat(result.next()).isTrue();
            return result.getLong(1);
        }
    }

    private void execute(String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    @Configuration(proxyBeanMethods = false)
    @Import(MyBatisConfig.class)
    static class TestConfig {

        @Bean
        DataSource dataSource() {
            JdbcDataSource h2 = new JdbcDataSource();
            h2.setURL("jdbc:h2:mem:normal_group_creation_mapper_test;MODE=MySQL;"
                    + "DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
            h2.setUser("sa");
            h2.setPassword("");
            return h2;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(
                DataSource dataSource,
                MybatisPlusInterceptor interceptor) throws Exception {
            MybatisConfiguration configuration = new MybatisConfiguration();
            configuration.setMapUnderscoreToCamelCase(true);
            MybatisSqlSessionFactoryBean factory = new MybatisSqlSessionFactoryBean();
            factory.setDataSource(dataSource);
            factory.setConfiguration(configuration);
            factory.setPlugins(interceptor);
            factory.setMapperLocations(new ClassPathResource(
                    "mapper/group/normalcreation/NormalGroupCreationMapper.xml"));
            return factory.getObject();
        }

        @Bean
        SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory factory) {
            return new SqlSessionTemplate(factory);
        }

        @Bean
        NormalGroupCreationMapper mapper(SqlSessionTemplate template) {
            return template.getMapper(NormalGroupCreationMapper.class);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }
    }
}
