package com.armada.account.service;

import static org.assertj.core.api.Assertions.assertThat;

import com.armada.account.mapper.AccountMapper;
import com.armada.account.service.impl.AccountProtocolLookupServiceImpl;
import com.armada.boot.config.MyBatisConfig;
import com.armada.platform.protocol.model.command.ProtocolAccountRef;
import com.armada.platform.protocol.model.enums.ProtocolBackend;
import com.armada.shared.tenant.TenantContext;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestExecutionListeners;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;

/** 拉手候选和最终命令复核必须真实执行 AccountMapper XML。 */
@SpringJUnitConfig(AccountPullerEligibilityMapperH2Test.TestConfig.class)
@TestExecutionListeners(
        listeners = DependencyInjectionTestExecutionListener.class,
        inheritListeners = false)
class AccountPullerEligibilityMapperH2Test {

    @Autowired private DataSource dataSource;
    @Autowired private AccountProtocolLookupService service;

    @BeforeEach
    void setUp() throws SQLException {
        execute("DROP ALL OBJECTS");
        execute("""
                CREATE TABLE account (
                  id BIGINT PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  ws_phone VARCHAR(32),
                  account_group_id BIGINT,
                  protocol_id VARCHAR(32),
                  protocol_account_id VARCHAR(64),
                  deleted_at BIGINT
                )
                """);
        execute("""
                CREATE TABLE account_state (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  account_id BIGINT NOT NULL,
                  account_state TINYINT,
                  login_state TINYINT,
                  risk_status TINYINT,
                  mute_status TINYINT
                )
                """);
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        seed(jdbc, 1L, 10L, 100L, 2, 1, null, "WEB");
        seed(jdbc, 1L, 11L, 100L, 2, 1, 2, "ANDROID");
        seed(jdbc, 1L, 12L, 100L, 2, 2, null, "WEB");
        seed(jdbc, 1L, 13L, 100L, 2, 1, 1, "ANDROID");
        seed(jdbc, 1L, 14L, 100L, 2, 1, 3, "WEB");
        seed(jdbc, 2L, 20L, 100L, 2, 1, null, "WEB");
        TenantContext.set(1L);
    }

    @AfterEach
    void tearDown() {
        TenantContext.clear();
    }

    @Test
    void groupSelectionAllowsMessageRestrictionButExcludesPullingRestriction() {
        assertThat(service.findOnlineNormalPullersByGroupId(100L))
                .containsExactly(
                        new ProtocolAccountRef(
                                10L, ProtocolBackend.WEB, "protocol-10", "phone-10"),
                        new ProtocolAccountRef(
                                13L, ProtocolBackend.ANDROID, "protocol-13", "phone-13"));
    }

    @Test
    void finalBoundaryUsesStatusRatherThanDeadlineAndPreservesRequestOrder() {
        assertThat(service.findEligiblePullerProtocolRefs(
                List.of(14L, 13L, 11L, 10L, 20L, 12L)))
                .containsExactly(
                        new ProtocolAccountRef(
                                13L, ProtocolBackend.ANDROID, "protocol-13", "phone-13"),
                        new ProtocolAccountRef(
                                10L, ProtocolBackend.WEB, "protocol-10", "phone-10"));
    }

    @Test
    void randomSelectionUsesTheCapabilitySpecificAllowedStatus() {
        assertThat(service.findRandomOnlineNormalByGroupId(100L))
                .get().extracting(ProtocolAccountRef::armadaAccountId)
                .isIn(10L, 11L);
        assertThat(service.findRandomOnlineNormalPullerByGroupId(100L))
                .get().extracting(ProtocolAccountRef::armadaAccountId)
                .isIn(10L, 13L);
    }

    private static void seed(
            JdbcTemplate jdbc,
            long tenantId,
            long accountId,
            long groupId,
            int lifecycle,
            int login,
            Integer operationRestriction,
            String protocolId) {
        jdbc.update("""
                INSERT INTO account (
                  id, tenant_id, ws_phone, account_group_id, protocol_id, protocol_account_id
                ) VALUES (?, ?, ?, ?, ?, ?)
                """, accountId, tenantId, "phone-" + accountId, groupId,
                protocolId, "protocol-" + accountId);
        jdbc.update("""
                INSERT INTO account_state (
                  tenant_id, account_id, account_state, login_state, mute_status
                ) VALUES (?, ?, ?, ?, ?)
                """, tenantId, accountId, lifecycle, login, operationRestriction);
    }

    private void execute(String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    @Configuration(proxyBeanMethods = false)
    @Import(MyBatisConfig.class)
    static class TestConfig {

        @Bean
        DataSource dataSource() {
            JdbcDataSource h2 = new JdbcDataSource();
            h2.setURL("jdbc:h2:mem:puller_eligibility_test;MODE=MySQL;"
                    + "DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
            h2.setUser("sa");
            h2.setPassword("");
            return h2;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(
                DataSource dataSource,
                MybatisPlusInterceptor interceptor) throws Exception {
            MybatisConfiguration configuration = new MybatisConfiguration();
            configuration.setMapUnderscoreToCamelCase(true);
            MybatisSqlSessionFactoryBean factory = new MybatisSqlSessionFactoryBean();
            factory.setDataSource(dataSource);
            factory.setConfiguration(configuration);
            factory.setPlugins(interceptor);
            factory.setMapperLocations(new ClassPathResource("mapper/account/AccountMapper.xml"));
            return factory.getObject();
        }

        @Bean
        SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory factory) {
            return new SqlSessionTemplate(factory);
        }

        @Bean
        AccountMapper accountMapper(SqlSessionTemplate template) {
            return template.getMapper(AccountMapper.class);
        }

        @Bean
        AccountProtocolLookupService accountProtocolLookupService(AccountMapper mapper) {
            return new AccountProtocolLookupServiceImpl(mapper);
        }
    }
}
