-- 补齐 country.name_en。英文地区名来源采用 Unicode CLDR/ICU en territory display names。
-- updated_at 固定为 2026-07-01 00:00:00 Asia/Shanghai 的 epoch 毫秒。
UPDATE country
SET name_en = CASE iso2
    WHEN 'AF' THEN 'Afghanistan'
    WHEN 'AX' THEN 'Åland Islands'
    WHEN 'AL' THEN 'Albania'
    WHEN 'DZ' THEN 'Algeria'
    WHEN 'AS' THEN 'American Samoa'
    WHEN 'AD' THEN 'Andorra'
    WHEN 'AO' THEN 'Angola'
    WHEN 'AI' THEN 'Anguilla'
    WHEN 'AQ' THEN 'Antarctica'
    WHEN 'AG' THEN 'Antigua & Barbuda'
    WHEN 'AR' THEN 'Argentina'
    WHEN 'AM' THEN 'Armenia'
    WHEN 'AW' THEN 'Aruba'
    WHEN 'AC' THEN 'Ascension Island'
    WHEN 'AU' THEN 'Australia'
    WHEN 'AT' THEN 'Austria'
    WHEN 'AZ' THEN 'Azerbaijan'
    WHEN 'BS' THEN 'Bahamas'
    WHEN 'BH' THEN 'Bahrain'
    WHEN 'BD' THEN 'Bangladesh'
    WHEN 'BB' THEN 'Barbados'
    WHEN 'BY' THEN 'Belarus'
    WHEN 'BE' THEN 'Belgium'
    WHEN 'BZ' THEN 'Belize'
    WHEN 'BJ' THEN 'Benin'
    WHEN 'BM' THEN 'Bermuda'
    WHEN 'BT' THEN 'Bhutan'
    WHEN 'BO' THEN 'Bolivia'
    WHEN 'BQ' THEN 'Caribbean Netherlands'
    WHEN 'BA' THEN 'Bosnia & Herzegovina'
    WHEN 'BW' THEN 'Botswana'
    WHEN 'BR' THEN 'Brazil'
    WHEN 'IO' THEN 'British Indian Ocean Territory'
    WHEN 'VG' THEN 'British Virgin Islands'
    WHEN 'BN' THEN 'Brunei'
    WHEN 'BG' THEN 'Bulgaria'
    WHEN 'BF' THEN 'Burkina Faso'
    WHEN 'BI' THEN 'Burundi'
    WHEN 'KH' THEN 'Cambodia'
    WHEN 'CM' THEN 'Cameroon'
    WHEN 'CA' THEN 'Canada'
    WHEN 'CV' THEN 'Cape Verde'
    WHEN 'KY' THEN 'Cayman Islands'
    WHEN 'CF' THEN 'Central African Republic'
    WHEN 'TD' THEN 'Chad'
    WHEN 'CL' THEN 'Chile'
    WHEN 'CN' THEN 'China'
    WHEN 'CX' THEN 'Christmas Island'
    WHEN 'CC' THEN 'Cocos (Keeling) Islands'
    WHEN 'CO' THEN 'Colombia'
    WHEN 'KM' THEN 'Comoros'
    WHEN 'CG' THEN 'Congo - Brazzaville'
    WHEN 'CD' THEN 'Congo - Kinshasa'
    WHEN 'CK' THEN 'Cook Islands'
    WHEN 'CR' THEN 'Costa Rica'
    WHEN 'CI' THEN 'Côte d’Ivoire'
    WHEN 'HR' THEN 'Croatia'
    WHEN 'CU' THEN 'Cuba'
    WHEN 'CW' THEN 'Curaçao'
    WHEN 'CY' THEN 'Cyprus'
    WHEN 'CZ' THEN 'Czechia'
    WHEN 'DK' THEN 'Denmark'
    WHEN 'DJ' THEN 'Djibouti'
    WHEN 'DM' THEN 'Dominica'
    WHEN 'DO' THEN 'Dominican Republic'
    WHEN 'EC' THEN 'Ecuador'
    WHEN 'EG' THEN 'Egypt'
    WHEN 'SV' THEN 'El Salvador'
    WHEN 'GQ' THEN 'Equatorial Guinea'
    WHEN 'ER' THEN 'Eritrea'
    WHEN 'EE' THEN 'Estonia'
    WHEN 'SZ' THEN 'Eswatini'
    WHEN 'ET' THEN 'Ethiopia'
    WHEN 'FK' THEN 'Falkland Islands'
    WHEN 'FO' THEN 'Faroe Islands'
    WHEN 'FJ' THEN 'Fiji'
    WHEN 'FI' THEN 'Finland'
    WHEN 'FR' THEN 'France'
    WHEN 'GF' THEN 'French Guiana'
    WHEN 'PF' THEN 'French Polynesia'
    WHEN 'GA' THEN 'Gabon'
    WHEN 'GM' THEN 'Gambia'
    WHEN 'GE' THEN 'Georgia'
    WHEN 'DE' THEN 'Germany'
    WHEN 'GH' THEN 'Ghana'
    WHEN 'GI' THEN 'Gibraltar'
    WHEN 'GR' THEN 'Greece'
    WHEN 'GL' THEN 'Greenland'
    WHEN 'GD' THEN 'Grenada'
    WHEN 'GP' THEN 'Guadeloupe'
    WHEN 'GU' THEN 'Guam'
    WHEN 'GT' THEN 'Guatemala'
    WHEN 'GG' THEN 'Guernsey'
    WHEN 'GN' THEN 'Guinea'
    WHEN 'GW' THEN 'Guinea-Bissau'
    WHEN 'GY' THEN 'Guyana'
    WHEN 'HT' THEN 'Haiti'
    WHEN 'HN' THEN 'Honduras'
    WHEN 'HK' THEN 'Hong Kong SAR China'
    WHEN 'HU' THEN 'Hungary'
    WHEN 'IS' THEN 'Iceland'
    WHEN 'IN' THEN 'India'
    WHEN 'ID' THEN 'Indonesia'
    WHEN 'IR' THEN 'Iran'
    WHEN 'IQ' THEN 'Iraq'
    WHEN 'IE' THEN 'Ireland'
    WHEN 'IM' THEN 'Isle of Man'
    WHEN 'IL' THEN 'Israel'
    WHEN 'IT' THEN 'Italy'
    WHEN 'JM' THEN 'Jamaica'
    WHEN 'JP' THEN 'Japan'
    WHEN 'JE' THEN 'Jersey'
    WHEN 'JO' THEN 'Jordan'
    WHEN 'KZ' THEN 'Kazakhstan'
    WHEN 'KE' THEN 'Kenya'
    WHEN 'KI' THEN 'Kiribati'
    WHEN 'XK' THEN 'Kosovo'
    WHEN 'KW' THEN 'Kuwait'
    WHEN 'KG' THEN 'Kyrgyzstan'
    WHEN 'LA' THEN 'Laos'
    WHEN 'LV' THEN 'Latvia'
    WHEN 'LB' THEN 'Lebanon'
    WHEN 'LS' THEN 'Lesotho'
    WHEN 'LR' THEN 'Liberia'
    WHEN 'LY' THEN 'Libya'
    WHEN 'LI' THEN 'Liechtenstein'
    WHEN 'LT' THEN 'Lithuania'
    WHEN 'LU' THEN 'Luxembourg'
    WHEN 'MO' THEN 'Macao SAR China'
    WHEN 'MG' THEN 'Madagascar'
    WHEN 'MW' THEN 'Malawi'
    WHEN 'MY' THEN 'Malaysia'
    WHEN 'MV' THEN 'Maldives'
    WHEN 'ML' THEN 'Mali'
    WHEN 'MT' THEN 'Malta'
    WHEN 'MH' THEN 'Marshall Islands'
    WHEN 'MQ' THEN 'Martinique'
    WHEN 'MR' THEN 'Mauritania'
    WHEN 'MU' THEN 'Mauritius'
    WHEN 'YT' THEN 'Mayotte'
    WHEN 'MX' THEN 'Mexico'
    WHEN 'FM' THEN 'Micronesia'
    WHEN 'MD' THEN 'Moldova'
    WHEN 'MC' THEN 'Monaco'
    WHEN 'MN' THEN 'Mongolia'
    WHEN 'ME' THEN 'Montenegro'
    WHEN 'MS' THEN 'Montserrat'
    WHEN 'MA' THEN 'Morocco'
    WHEN 'MZ' THEN 'Mozambique'
    WHEN 'MM' THEN 'Myanmar (Burma)'
    WHEN 'NA' THEN 'Namibia'
    WHEN 'NR' THEN 'Nauru'
    WHEN 'NP' THEN 'Nepal'
    WHEN 'NL' THEN 'Netherlands'
    WHEN 'NC' THEN 'New Caledonia'
    WHEN 'NZ' THEN 'New Zealand'
    WHEN 'NI' THEN 'Nicaragua'
    WHEN 'NE' THEN 'Niger'
    WHEN 'NG' THEN 'Nigeria'
    WHEN 'NU' THEN 'Niue'
    WHEN 'NF' THEN 'Norfolk Island'
    WHEN 'KP' THEN 'North Korea'
    WHEN 'MK' THEN 'North Macedonia'
    WHEN 'MP' THEN 'Northern Mariana Islands'
    WHEN 'NO' THEN 'Norway'
    WHEN 'OM' THEN 'Oman'
    WHEN 'PK' THEN 'Pakistan'
    WHEN 'PW' THEN 'Palau'
    WHEN 'PS' THEN 'Palestinian Territories'
    WHEN 'PA' THEN 'Panama'
    WHEN 'PG' THEN 'Papua New Guinea'
    WHEN 'PY' THEN 'Paraguay'
    WHEN 'PE' THEN 'Peru'
    WHEN 'PH' THEN 'Philippines'
    WHEN 'PN' THEN 'Pitcairn Islands'
    WHEN 'PL' THEN 'Poland'
    WHEN 'PT' THEN 'Portugal'
    WHEN 'PR' THEN 'Puerto Rico'
    WHEN 'QA' THEN 'Qatar'
    WHEN 'RE' THEN 'Réunion'
    WHEN 'RO' THEN 'Romania'
    WHEN 'RU' THEN 'Russia'
    WHEN 'RW' THEN 'Rwanda'
    WHEN 'BL' THEN 'St. Barthélemy'
    WHEN 'SH' THEN 'St. Helena'
    WHEN 'KN' THEN 'St. Kitts & Nevis'
    WHEN 'LC' THEN 'St. Lucia'
    WHEN 'MF' THEN 'St. Martin'
    WHEN 'PM' THEN 'St. Pierre & Miquelon'
    WHEN 'VC' THEN 'St. Vincent & Grenadines'
    WHEN 'WS' THEN 'Samoa'
    WHEN 'SM' THEN 'San Marino'
    WHEN 'ST' THEN 'São Tomé & Príncipe'
    WHEN 'SA' THEN 'Saudi Arabia'
    WHEN 'SN' THEN 'Senegal'
    WHEN 'RS' THEN 'Serbia'
    WHEN 'SC' THEN 'Seychelles'
    WHEN 'SL' THEN 'Sierra Leone'
    WHEN 'SG' THEN 'Singapore'
    WHEN 'SX' THEN 'Sint Maarten'
    WHEN 'SK' THEN 'Slovakia'
    WHEN 'SI' THEN 'Slovenia'
    WHEN 'SB' THEN 'Solomon Islands'
    WHEN 'SO' THEN 'Somalia'
    WHEN 'ZA' THEN 'South Africa'
    WHEN 'GS' THEN 'South Georgia & South Sandwich Islands'
    WHEN 'KR' THEN 'South Korea'
    WHEN 'SS' THEN 'South Sudan'
    WHEN 'ES' THEN 'Spain'
    WHEN 'LK' THEN 'Sri Lanka'
    WHEN 'SD' THEN 'Sudan'
    WHEN 'SR' THEN 'Suriname'
    WHEN 'SJ' THEN 'Svalbard & Jan Mayen'
    WHEN 'SE' THEN 'Sweden'
    WHEN 'CH' THEN 'Switzerland'
    WHEN 'SY' THEN 'Syria'
    WHEN 'TW' THEN 'Taiwan'
    WHEN 'TJ' THEN 'Tajikistan'
    WHEN 'TZ' THEN 'Tanzania'
    WHEN 'TH' THEN 'Thailand'
    WHEN 'TL' THEN 'Timor-Leste'
    WHEN 'TG' THEN 'Togo'
    WHEN 'TK' THEN 'Tokelau'
    WHEN 'TO' THEN 'Tonga'
    WHEN 'TT' THEN 'Trinidad & Tobago'
    WHEN 'TA' THEN 'Tristan da Cunha'
    WHEN 'TN' THEN 'Tunisia'
    WHEN 'TR' THEN 'Türkiye'
    WHEN 'TM' THEN 'Turkmenistan'
    WHEN 'TC' THEN 'Turks & Caicos Islands'
    WHEN 'TV' THEN 'Tuvalu'
    WHEN 'UG' THEN 'Uganda'
    WHEN 'UA' THEN 'Ukraine'
    WHEN 'AE' THEN 'United Arab Emirates'
    WHEN 'GB' THEN 'United Kingdom'
    WHEN 'US' THEN 'United States'
    WHEN 'UY' THEN 'Uruguay'
    WHEN 'VI' THEN 'U.S. Virgin Islands'
    WHEN 'UZ' THEN 'Uzbekistan'
    WHEN 'VU' THEN 'Vanuatu'
    WHEN 'VA' THEN 'Vatican City'
    WHEN 'VE' THEN 'Venezuela'
    WHEN 'VN' THEN 'Vietnam'
    WHEN 'WF' THEN 'Wallis & Futuna'
    WHEN 'EH' THEN 'Western Sahara'
    WHEN 'YE' THEN 'Yemen'
    WHEN 'ZM' THEN 'Zambia'
    WHEN 'ZW' THEN 'Zimbabwe'
    ELSE name_en
END,
    updated_at = 1782835200000
WHERE deleted_at IS NULL
  AND iso2 IN ('AF', 'AX', 'AL', 'DZ', 'AS', 'AD', 'AO', 'AI', 'AQ', 'AG', 'AR', 'AM', 'AW', 'AC', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BM', 'BT', 'BO', 'BQ', 'BA', 'BW', 'BR', 'IO', 'VG', 'BN', 'BG', 'BF', 'BI', 'KH', 'CM', 'CA', 'CV', 'KY', 'CF', 'TD', 'CL', 'CN', 'CX', 'CC', 'CO', 'KM', 'CG', 'CD', 'CK', 'CR', 'CI', 'HR', 'CU', 'CW', 'CY', 'CZ', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'SZ', 'ET', 'FK', 'FO', 'FJ', 'FI', 'FR', 'GF', 'PF', 'GA', 'GM', 'GE', 'DE', 'GH', 'GI', 'GR', 'GL', 'GD', 'GP', 'GU', 'GT', 'GG', 'GN', 'GW', 'GY', 'HT', 'HN', 'HK', 'HU', 'IS', 'IN', 'ID', 'IR', 'IQ', 'IE', 'IM', 'IL', 'IT', 'JM', 'JP', 'JE', 'JO', 'KZ', 'KE', 'KI', 'XK', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MO', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MQ', 'MR', 'MU', 'YT', 'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MS', 'MA', 'MZ', 'MM', 'NA', 'NR', 'NP', 'NL', 'NC', 'NZ', 'NI', 'NE', 'NG', 'NU', 'NF', 'KP', 'MK', 'MP', 'NO', 'OM', 'PK', 'PW', 'PS', 'PA', 'PG', 'PY', 'PE', 'PH', 'PN', 'PL', 'PT', 'PR', 'QA', 'RE', 'RO', 'RU', 'RW', 'BL', 'SH', 'KN', 'LC', 'MF', 'PM', 'VC', 'WS', 'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SX', 'SK', 'SI', 'SB', 'SO', 'ZA', 'GS', 'KR', 'SS', 'ES', 'LK', 'SD', 'SR', 'SJ', 'SE', 'CH', 'SY', 'TW', 'TJ', 'TZ', 'TH', 'TL', 'TG', 'TK', 'TO', 'TT', 'TA', 'TN', 'TR', 'TM', 'TC', 'TV', 'UG', 'UA', 'AE', 'GB', 'US', 'UY', 'VI', 'UZ', 'VU', 'VA', 'VE', 'VN', 'WF', 'EH', 'YE', 'ZM', 'ZW');
