CREATE TABLE account_online_attempt_log (
    id                         BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
    tenant_id                  BIGINT       NOT NULL                COMMENT '租户ID',
    account_id                 BIGINT       NOT NULL                COMMENT 'Armada账号ID',
    protocol_account_id        VARCHAR(128) NOT NULL                COMMENT '协议层账号ID',
    online_attempt_id          VARCHAR(64)  NOT NULL                COMMENT '本次上线尝试ID',
    previous_online_attempt_id VARCHAR(64)           DEFAULT NULL   COMMENT '上一轮上线尝试ID',
    command_id                 VARCHAR(64)           DEFAULT NULL   COMMENT '协议命令ID',
    batch_id                   VARCHAR(64)           DEFAULT NULL   COMMENT '批量命令ID',
    proxy_id                   BIGINT                DEFAULT NULL   COMMENT '本次使用的代理ID',
    source                     VARCHAR(64)           DEFAULT NULL   COMMENT '上线来源',
    from_state                 VARCHAR(32)           DEFAULT NULL   COMMENT '协议层原状态',
    to_state                   VARCHAR(32)           DEFAULT NULL   COMMENT '协议层目标状态',
    diagnosis_code             VARCHAR(64)  NOT NULL                COMMENT '诊断码',
    diagnosis_class            VARCHAR(64)  NOT NULL                COMMENT '诊断分类',
    raw_code                   INT                   DEFAULT NULL   COMMENT '协议层原始错误码',
    raw_reason                 VARCHAR(512)          DEFAULT NULL   COMMENT '协议层原始原因,已截断',
    recoverability             VARCHAR(32)           DEFAULT NULL   COMMENT '是否可重试',
    action_taken               VARCHAR(64)           DEFAULT NULL   COMMENT '协议层已执行动作',
    worker_id                  VARCHAR(64)           DEFAULT NULL   COMMENT '协议worker ID',
    evidence_json              JSON                  DEFAULT NULL   COMMENT '脱敏后的诊断证据',
    occurred_at                DATETIME(3)  NOT NULL                COMMENT '协议层事件发生时间',
    created_at                 DATETIME(3)  NOT NULL                COMMENT 'Armada落库时间',
    PRIMARY KEY (id),
    KEY idx_attempt (tenant_id, online_attempt_id),
    KEY idx_account_time (tenant_id, account_id, occurred_at),
    KEY idx_proxy_time (tenant_id, proxy_id, occurred_at),
    KEY idx_code_time (tenant_id, diagnosis_code, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账号上线尝试诊断时间线';
