CREATE TABLE IF NOT EXISTS group_creation_marketing_task (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    task_name VARCHAR(128) NOT NULL COMMENT '任务名称',
    account_group_id BIGINT NOT NULL COMMENT '账号分组ID',
    account_group_name VARCHAR(100) NOT NULL COMMENT '账号分组名称快照',
    marketing_template_id BIGINT NOT NULL COMMENT '营销模板ID',
    marketing_template_name VARCHAR(128) NOT NULL COMMENT '营销模板名称快照',
    marketing_task_id BIGINT DEFAULT NULL COMMENT '复用的营销任务ID',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1=待执行 2=执行中 3=成功 4=失败 5=部分失败 6=已停止',
    matched_item_count INT NOT NULL DEFAULT 0 COMMENT '匹配执行项数',
    unmatched_file_count INT NOT NULL DEFAULT 0 COMMENT '未匹配文件数',
    success_count INT NOT NULL DEFAULT 0 COMMENT '成功执行项数',
    failed_count INT NOT NULL DEFAULT 0 COMMENT '失败执行项数',
    abandoned_count INT NOT NULL DEFAULT 0 COMMENT '放弃执行项数',
    send_interval_seconds INT NOT NULL DEFAULT 30 COMMENT '持续营销发送间隔秒数',
    group_name_prefix VARCHAR(100) DEFAULT NULL COMMENT '群名前缀',
    remark VARCHAR(512) DEFAULT NULL COMMENT '备注',
    created_by BIGINT DEFAULT NULL COMMENT '创建人',
    created_at BIGINT NOT NULL COMMENT '创建时间(epoch毫秒)',
    updated_at BIGINT NOT NULL COMMENT '更新时间(epoch毫秒)',
    finished_at BIGINT DEFAULT NULL COMMENT '完成时间(epoch毫秒)',
    deleted_at BIGINT DEFAULT NULL COMMENT '软删时间(epoch毫秒)',
    PRIMARY KEY (id),
    KEY idx_gcm_task_tenant (tenant_id, deleted_at, id),
    KEY idx_gcm_task_status (tenant_id, status, id),
    KEY idx_gcm_task_template (tenant_id, marketing_template_id),
    KEY idx_gcm_task_marketing_task (tenant_id, marketing_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='建群营销任务';

CREATE TABLE IF NOT EXISTS group_creation_marketing_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    tenant_id BIGINT NOT NULL COMMENT '租户ID',
    task_id BIGINT NOT NULL COMMENT '建群营销任务ID',
    file_index INT NOT NULL COMMENT '上传文件顺序,从0开始',
    file_name VARCHAR(255) NOT NULL COMMENT '上传文件名',
    material_content LONGTEXT NOT NULL COMMENT '规范化后的号码文本,每行一个',
    participant_count INT NOT NULL DEFAULT 0 COMMENT '号码数',
    account_id BIGINT NOT NULL COMMENT '执行账号ID',
    account_phone VARCHAR(32) NOT NULL COMMENT '账号号码快照',
    protocol_account_id VARCHAR(128) DEFAULT NULL COMMENT '协议账号ID快照',
    group_subject VARCHAR(100) NOT NULL COMMENT '实际建群名称',
    group_jid VARCHAR(128) DEFAULT NULL COMMENT '协议返回群JID',
    group_link_id BIGINT DEFAULT NULL COMMENT '本地群入口ID',
    participant_result_json JSON DEFAULT NULL COMMENT '建群逐成员结果摘要',
    marketing_task_id BIGINT DEFAULT NULL COMMENT '复用的营销任务ID',
    marketing_target_id BIGINT DEFAULT NULL COMMENT '复用的营销目标ID',
    marketing_attempt_id BIGINT DEFAULT NULL COMMENT '复用的营销发送尝试ID',
    command_id VARCHAR(64) DEFAULT NULL COMMENT '营销发送协议命令ID',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1=待执行 2=建群中 3=营销发送中 4=成功 5=失败 6=放弃',
    reason_code VARCHAR(64) DEFAULT NULL COMMENT '原因码',
    reason_message VARCHAR(255) DEFAULT NULL COMMENT '原因描述',
    next_run_at BIGINT NOT NULL DEFAULT 0 COMMENT '下一次可执行时间(epoch毫秒)',
    started_at BIGINT DEFAULT NULL COMMENT '开始时间(epoch毫秒)',
    finished_at BIGINT DEFAULT NULL COMMENT '完成时间(epoch毫秒)',
    created_at BIGINT NOT NULL COMMENT '创建时间(epoch毫秒)',
    updated_at BIGINT NOT NULL COMMENT '更新时间(epoch毫秒)',
    PRIMARY KEY (id),
    UNIQUE KEY uq_gcm_item_file (tenant_id, task_id, file_index),
    KEY idx_gcm_item_due (tenant_id, status, next_run_at, id),
    KEY idx_gcm_item_task (tenant_id, task_id, id),
    KEY idx_gcm_item_attempt (tenant_id, marketing_attempt_id),
    KEY idx_gcm_item_account (tenant_id, account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='建群营销执行项';
