-- 推广配对正式 Facebook CAPI 事件 Outbox；业务事务只记录事件，后台异步投递 Meta。
CREATE TABLE promotion_capi_event_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Outbox主键',
    tenant_id BIGINT NOT NULL COMMENT '渠道所属租户ID',
    promotion_channel_id BIGINT NOT NULL COMMENT '推广渠道ID快照',
    pairing_session_id BIGINT NOT NULL COMMENT '推广配对会话ID',
    event_stage TINYINT NOT NULL COMMENT '业务阶段:1意向用户 2请求登录 3登录成功',
    event_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Meta官方标准事件代码快照',
    event_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Meta幂等事件ID,重试保持不变',
    event_time BIGINT DEFAULT NULL COMMENT '业务触发时间(epoch秒);等待触发时为空',
    phone_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT 'E.164手机号SHA-256;终态清理',
    client_ip VARCHAR(45) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT '客户端IPv4/IPv6;终态清理',
    client_user_agent VARCHAR(512) DEFAULT NULL COMMENT '客户端User-Agent;终态清理',
    fbp VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT 'Meta _fbp归因值;终态清理',
    fbc VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT 'Meta _fbc归因值;终态清理',
    event_source_url VARCHAR(2048) DEFAULT NULL COMMENT 'HTTP/HTTPS落地页URL;终态清理',
    status TINYINT NOT NULL COMMENT '状态:0等待触发 1待发送 2发送中 3成功 4永久失败 5取消',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '已发生的投递重试次数',
    next_retry_at BIGINT NOT NULL DEFAULT 0 COMMENT '下次可投递时间(epoch毫秒)',
    locked_by VARCHAR(64) DEFAULT NULL COMMENT '当前投递实例',
    locked_at BIGINT DEFAULT NULL COMMENT '领取时间(epoch毫秒)',
    sent_at BIGINT DEFAULT NULL COMMENT 'Meta确认接收时间(epoch毫秒)',
    last_error_code VARCHAR(64) DEFAULT NULL COMMENT '稳定脱敏错误码',
    last_error_message VARCHAR(255) DEFAULT NULL COMMENT '截断脱敏错误摘要',
    sensitive_expires_at BIGINT NOT NULL COMMENT '匹配字段强制清理截止时间(epoch毫秒)',
    created_at BIGINT NOT NULL COMMENT '创建时间(epoch毫秒)',
    updated_at BIGINT NOT NULL COMMENT '更新时间(epoch毫秒)',
    PRIMARY KEY (id),
    UNIQUE KEY uq_promotion_capi_session_stage (tenant_id, pairing_session_id, event_stage),
    UNIQUE KEY uq_promotion_capi_event_id (event_id),
    KEY idx_promotion_capi_dispatch (status, next_retry_at, id),
    KEY idx_promotion_capi_lock_recovery (status, locked_at, id),
    KEY idx_promotion_capi_sensitive_expiry (sensitive_expires_at, id),
    KEY idx_promotion_capi_channel (tenant_id, promotion_channel_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='推广配对Facebook CAPI事件Outbox';
