CREATE TABLE IF NOT EXISTS account_mutual_contact_task (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
 tenant_id BIGINT NOT NULL COMMENT '租户ID',
 created_by BIGINT NOT NULL COMMENT '发起人及数据归属',
 request_id VARCHAR(64) NOT NULL COMMENT '创建幂等键',
 left_group_id BIGINT NOT NULL COMMENT '左侧分组快照',
 right_group_id BIGINT NOT NULL COMMENT '右侧分组快照',
 left_group_name VARCHAR(100) NOT NULL COMMENT '左侧分组名称快照',
 right_group_name VARCHAR(100) NOT NULL COMMENT '右侧分组名称快照',
 left_count INT NOT NULL COMMENT '左侧参与数',
 right_count INT NOT NULL COMMENT '右侧参与数',
 interval_seconds INT NOT NULL DEFAULT 0 COMMENT '每次完成后单账号额外等待秒数',
 status TINYINT NOT NULL DEFAULT 1 COMMENT '1执行中2已停止3全部成功4需关注',
 created_at BIGINT NOT NULL COMMENT '创建时间',
 updated_at BIGINT NOT NULL COMMENT '更新时间',
 PRIMARY KEY (id),
 UNIQUE KEY uq_mutual_request (tenant_id,created_by,request_id),
 KEY idx_mutual_task_page (tenant_id,created_at,id)
) COMMENT='两个账号分组互相保存联系人任务';

CREATE TABLE IF NOT EXISTS account_mutual_contact_item (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '定向操作ID',
 tenant_id BIGINT NOT NULL COMMENT '租户ID',
 task_id BIGINT NOT NULL COMMENT '互存任务ID',
 actor_id BIGINT NOT NULL COMMENT '执行账号ID快照',
 target_id BIGINT NOT NULL COMMENT '目标账号ID快照',
 actor_phone VARCHAR(32) NOT NULL COMMENT '执行方WS号快照',
 target_phone VARCHAR(32) NOT NULL COMMENT '目标方WS号及保存名称快照',
 protocol_account_id VARCHAR(64) NOT NULL COMMENT '执行方协议句柄快照',
 protocol_backend VARCHAR(16) NOT NULL COMMENT '执行方协议WEB或ANDROID',
 status TINYINT NOT NULL DEFAULT 1 COMMENT '1待执行2已提交3成功4失败5待确认6取消',
 command_id VARCHAR(64) NULL COMMENT '当前命令ID，晚到结果按此关联',
 attempt_no INT NOT NULL DEFAULT 0 COMMENT '当前派发次数',
 retryable TINYINT NOT NULL DEFAULT 0 COMMENT '明确失败是否允许人工重试',
 reason_code VARCHAR(64) NULL COMMENT '结果原因码，不存协议原始敏感信息',
 submitted_at BIGINT NULL COMMENT '提交时间',
 result_at BIGINT NULL COMMENT '结果处理时间',
 next_execute_at BIGINT NOT NULL DEFAULT 0 COMMENT '同账号后继动作冷却水位',
 created_at BIGINT NOT NULL COMMENT '创建时间',
 updated_at BIGINT NOT NULL COMMENT '更新时间',
 PRIMARY KEY (id),
 UNIQUE KEY uq_mutual_direction (tenant_id,task_id,actor_id,target_id),
 UNIQUE KEY uq_mutual_command (command_id),
 KEY idx_mutual_actor (tenant_id,actor_id,status,next_execute_at),
 KEY idx_mutual_task_item (tenant_id,task_id,status,id)
) COMMENT='互存任务单方向保存事实';
