package com.armada.group.normalcreation.service.impl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.armada.group.normalcreation.mapper.NormalGroupCreationMapper;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.ItemWork;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.SecondaryAdminWork;
import com.armada.platform.protocol.model.command.ProtocolNormalGroupCreationReference;
import com.armada.platform.protocol.model.entity.ProtocolCommandOutbox;
import com.armada.shared.tenant.TenantContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

class NormalGroupCreationPayloadHydratorTest {

    private final NormalGroupCreationMapper mapper = mock(NormalGroupCreationMapper.class);
    private final ObjectMapper objectMapper = new ObjectMapper();
    private final NormalGroupCreationPayloadHydrator hydrator =
            new NormalGroupCreationPayloadHydrator(mapper, objectMapper);

    @AfterEach
    void clearTenant() {
        TenantContext.clear();
    }

    @Test
    void settingsPayloadMarksBlankTemplateAsAutomaticallyGenerated() {
        ProtocolCommandOutbox row = outbox();
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "ABCDEFGHI01234", "",
                382L, "creator-web", "WEB", "911",
                "120363000001234@g.us", "RUNNING", "APPLYING_SETTINGS", "SENT",
                "cmd-create", "cmd-settings", null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of());
        JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                1L, 9L, 21L, null, null, "GROUP_SETTINGS_APPLY", "normal_group_creation"));

        JsonNode payload = hydrator.hydrate(row, reference);

        assertThat(payload.path("subject").asText()).isEqualTo("ABCDEFGHI01234");
        assertThat(payload.path("autoGeneratedSubject").asBoolean()).isTrue();
    }

    @Test
    void createPayloadContainsSecondaryAdminsAndOrdinaryMembersExactlyOnce() {
        ProtocolCommandOutbox row = outbox("cmd-create");
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "测试普群", "测试普群",
                382L, "creator-web", "WEB", "911",
                null, "RUNNING", "CREATING_GROUP", "SENT",
                "cmd-create", null, null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of(
                new com.armada.group.normalcreation.model.NormalGroupCreationRecords.MemberWork(
                        31L, 383L, "member-android", "ANDROID", "922",
                        "SUCCESS", "SUCCESS", "c1", "c2", "PENDING")));
        when(mapper.selectSecondaryAdminWorks(21L)).thenReturn(List.of(
                secondaryAdmin(41L, 384L, "933"),
                secondaryAdmin(42L, 385L, "944")));
        JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                1L, 9L, 21L, null, null, "GROUP_CREATE", "normal_group_creation"));

        JsonNode payload = hydrator.hydrate(row, reference);

        assertThat(payload.path("participants").toString())
                .isEqualTo("[\"933\",\"944\",\"922\"]");
        assertThat(payload.has("secondaryAdmins")).isFalse();
    }

    @Test
    void secondaryContactPayloadMapsInternalDirectionToExistingProtocolDirection() {
        ProtocolCommandOutbox row = outbox("c3");
        row.setProtocolAccountId("acc_384");
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "测试普群", "测试普群",
                382L, "creator-web", "WEB", "911",
                null, "RUNNING", "PREPARING_CONTACTS", "SENT",
                null, null, null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of());
        when(mapper.selectSecondaryAdminWorks(21L)).thenReturn(List.of(
                secondaryAdmin(41L, 384L, "933")));
        JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                1L, 9L, 21L, 41L, "SECONDARY_SAVE_ANCHOR",
                "CONTACT_PREPARE", "normal_group_creation"));

        JsonNode payload = hydrator.hydrate(row, reference);

        assertThat(payload.path("direction").asText()).isEqualTo("CREATOR_SAVE_MEMBER");
        assertThat(payload.path("accountId").asLong()).isEqualTo(384L);
        assertThat(payload.path("contact").asText()).isEqualTo("922");
    }

    private static SecondaryAdminWork secondaryAdmin(Long id, Long accountId, String phone) {
        return new SecondaryAdminWork(
                id, accountId, "acc_" + accountId, "WEB", phone,
                383L, "member-android", "ANDROID", "922",
                "SUCCESS", "SUCCESS", "SUCCESS", "SUCCESS",
                "c1", "c2", "c3", "c4", "PENDING", "PENDING", null);
    }

    private static ProtocolCommandOutbox outbox() {
        return outbox("cmd-settings");
    }

    private static ProtocolCommandOutbox outbox(String commandId) {
        ProtocolCommandOutbox row = new ProtocolCommandOutbox();
        row.setTenantId(1L);
        row.setCommandId(commandId);
        row.setCommandType("group.normal_creation.requested");
        row.setAggregateType("NORMAL_GROUP_CREATION_ITEM");
        row.setAggregateId(21L);
        row.setProtocolAccountId("creator-web");
        row.setProtocolBackend("WEB");
        return row;
    }
}
