package com.armada.group.normalcreation.service.impl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.armada.group.normalcreation.mapper.NormalGroupCreationMapper;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.ItemWork;
import com.armada.platform.protocol.model.command.ProtocolNormalGroupCreationReference;
import com.armada.platform.protocol.model.entity.ProtocolCommandOutbox;
import com.armada.shared.tenant.TenantContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

class NormalGroupCreationPayloadHydratorTest {

    private final NormalGroupCreationMapper mapper = mock(NormalGroupCreationMapper.class);
    private final ObjectMapper objectMapper = new ObjectMapper();
    private final NormalGroupCreationPayloadHydrator hydrator =
            new NormalGroupCreationPayloadHydrator(mapper, objectMapper);

    @AfterEach
    void clearTenant() {
        TenantContext.clear();
    }

    @Test
    void settingsPayloadMarksBlankTemplateAsAutomaticallyGenerated() {
        ProtocolCommandOutbox row = outbox();
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "ABCDEFGHI01234", "",
                382L, "creator-web", "WEB", "911",
                "120363000001234@g.us", "RUNNING", "APPLYING_SETTINGS", "SENT",
                "cmd-create", "cmd-settings", null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of());
        JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                1L, 9L, 21L, null, null, "GROUP_SETTINGS_APPLY", "normal_group_creation"));

        JsonNode payload = hydrator.hydrate(row, reference);

        assertThat(payload.path("subject").asText()).isEqualTo("ABCDEFGHI01234");
        assertThat(payload.path("autoGeneratedSubject").asBoolean()).isTrue();
    }

    private static ProtocolCommandOutbox outbox() {
        ProtocolCommandOutbox row = new ProtocolCommandOutbox();
        row.setTenantId(1L);
        row.setCommandId("cmd-settings");
        row.setCommandType("group.normal_creation.requested");
        row.setAggregateType("NORMAL_GROUP_CREATION_ITEM");
        row.setAggregateId(21L);
        row.setProtocolAccountId("creator-web");
        row.setProtocolBackend("WEB");
        return row;
    }
}
