package com.armada.group.normalcreation.service.impl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.armada.group.normalcreation.mapper.NormalGroupCreationMapper;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.ItemWork;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.MemberWork;
import com.armada.group.normalcreation.model.NormalGroupCreationRecords.SecondaryAdminWork;
import com.armada.platform.protocol.model.command.ProtocolNormalGroupCreationReference;
import com.armada.platform.protocol.model.entity.ProtocolCommandOutbox;
import com.armada.shared.tenant.TenantContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

class NormalGroupCreationPayloadHydratorTest {

    private final NormalGroupCreationMapper mapper = mock(NormalGroupCreationMapper.class);
    private final ObjectMapper objectMapper = new ObjectMapper();
    private final NormalGroupCreationPayloadHydrator hydrator =
            new NormalGroupCreationPayloadHydrator(mapper, objectMapper);

    @AfterEach
    void clearTenant() {
        TenantContext.clear();
    }

    @Test
    void settingsPayloadMarksBlankTemplateAsAutomaticallyGenerated() {
        ProtocolCommandOutbox row = outbox();
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "ABCDEFGHI01234", "",
                382L, "creator-web", "WEB", "911",
                "120363000001234@g.us", "RUNNING", "APPLYING_SETTINGS", "SENT",
                "cmd-create", "cmd-settings", null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of());
        JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                1L, 9L, 21L, null, null, "GROUP_SETTINGS_APPLY", "normal_group_creation"));

        JsonNode payload = hydrator.hydrate(row, reference);

        assertThat(payload.path("subject").asText()).isEqualTo("ABCDEFGHI01234");
        assertThat(payload.path("autoGeneratedSubject").asBoolean()).isTrue();
    }

    @Test
    void createPayloadContainsSecondaryAdminsAndOrdinaryMembersExactlyOnce() {
        ProtocolCommandOutbox row = outbox("cmd-create");
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "测试普群", "测试普群",
                382L, "creator-web", "WEB", "911",
                null, "RUNNING", "CREATING_GROUP", "SENT",
                "cmd-create", null, null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of(
                new com.armada.group.normalcreation.model.NormalGroupCreationRecords.MemberWork(
                        31L, 383L, "member-android", "ANDROID", "922",
                        "SUCCESS", "SUCCESS", "c1", "c2", "PENDING")));
        when(mapper.selectSecondaryAdminWorks(21L)).thenReturn(List.of(
                secondaryAdmin(41L, 384L, "933"),
                secondaryAdmin(42L, 385L, "944")));
        JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                1L, 9L, 21L, null, null, "GROUP_CREATE", "normal_group_creation"));

        JsonNode payload = hydrator.hydrate(row, reference);

        assertThat(payload.path("participants").toString())
                .isEqualTo("[\"933\",\"944\",\"922\"]");
        assertThat(payload.has("secondaryAdmins")).isFalse();
    }

    @Test
    void createPayloadOnlyContainsAccountsWithMutualCreatorContacts() {
        ProtocolCommandOutbox row = outbox("cmd-create");
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "测试普群", "测试普群",
                382L, "creator-web", "WEB", "911",
                null, "RUNNING", "CREATING_GROUP", "SENT",
                "cmd-create", null, null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of(
                new MemberWork(
                        31L, 383L, "member-1", "ANDROID", "922",
                        "SUCCESS", "SUCCESS", "m1", "m2", "PENDING"),
                new MemberWork(
                        32L, 384L, "member-2", "ANDROID", "923",
                        "FAILED", "SUCCESS", "m3", "m4", "PENDING"),
                new MemberWork(
                        33L, 385L, "member-3", "WEB", "924",
                        "SUCCESS", "FAILED", "m5", "m6", "PENDING")));
        when(mapper.selectSecondaryAdminWorks(21L)).thenReturn(List.of(
                secondaryAdmin(41L, 386L, "933"),
                new SecondaryAdminWork(
                        42L, 387L, "acc_387", "WEB", "944",
                        383L, "member-1", "ANDROID", "922",
                        "FAILED", "SUCCESS", "SUCCESS", "SUCCESS",
                        "s1", "s2", "s3", "s4", "PENDING", "PENDING", null)));
        JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                1L, 9L, 21L, null, null, "GROUP_CREATE", "normal_group_creation"));

        JsonNode payload = hydrator.hydrate(row, reference);

        assertThat(payload.path("participants").toString())
                .isEqualTo("[\"933\",\"922\"]");
    }

    @Test
    void createPayloadRejectsEmptyEligibleParticipantList() {
        ProtocolCommandOutbox row = outbox("cmd-create");
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "测试普群", "测试普群",
                382L, "creator-web", "WEB", "911",
                null, "RUNNING", "CREATING_GROUP", "SENT",
                "cmd-create", null, null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of(new MemberWork(
                31L, 383L, "member-1", "ANDROID", "922",
                "FAILED", "UNKNOWN", "m1", "m2", "PENDING")));
        when(mapper.selectSecondaryAdminWorks(21L)).thenReturn(List.of());
        JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                1L, 9L, 21L, null, null, "GROUP_CREATE", "normal_group_creation"));

        assertThatThrownBy(() -> hydrator.hydrate(row, reference))
                .isInstanceOf(com.armada.shared.exception.BusinessException.class)
                .hasMessageContaining("建群参与者为空");
    }

    @Test
    void secondaryContactPayloadMapsInternalDirectionToExistingProtocolDirection() {
        ProtocolCommandOutbox row = outbox("c3");
        row.setProtocolAccountId("acc_384");
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "测试普群", "测试普群",
                382L, "creator-web", "WEB", "911",
                null, "RUNNING", "PREPARING_CONTACTS", "SENT",
                null, null, null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of());
        when(mapper.selectSecondaryAdminWorks(21L)).thenReturn(List.of(
                secondaryAdmin(41L, 384L, "933")));
        JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                1L, 9L, 21L, 41L, "SECONDARY_SAVE_ANCHOR",
                "CONTACT_PREPARE", "normal_group_creation"));

        JsonNode payload = hydrator.hydrate(row, reference);

        assertThat(payload.path("direction").asText()).isEqualTo("CREATOR_SAVE_MEMBER");
        assertThat(payload.path("accountId").asLong()).isEqualTo(384L);
        assertThat(payload.path("contact").asText()).isEqualTo("922");
    }

    @Test
    void contactPayloadMapsActorAndTargetForEveryDirection() {
        ItemWork item = new ItemWork(
                21L, 1L, 9L, "测试普群", "测试普群",
                382L, "creator-web", "WEB", "911",
                null, "RUNNING", "PREPARING_CONTACTS", "SENT",
                null, null, null, "KEEP", null, 91L, 92L,
                true, false, true, false, 0);
        when(mapper.selectItemWork(21L)).thenReturn(item);
        when(mapper.selectMemberWorks(21L)).thenReturn(List.of(
                new MemberWork(
                        31L, 383L, "member-android", "ANDROID", "922",
                        "PENDING", "PENDING", "member-c1", "member-c2", "PENDING")));
        when(mapper.selectSecondaryAdminWorks(21L)).thenReturn(List.of(
                secondaryAdmin(41L, 384L, "933")));
        List<ContactDirectionCase> cases = List.of(
                new ContactDirectionCase(
                        31L, "CREATOR_SAVE_MEMBER", "member-c1",
                        382L, "creator-web", "WEB", "911", "922", "CREATOR_SAVE_MEMBER"),
                new ContactDirectionCase(
                        31L, "MEMBER_SAVE_CREATOR", "member-c2",
                        383L, "member-android", "ANDROID", "922", "911", "MEMBER_SAVE_CREATOR"),
                new ContactDirectionCase(
                        41L, "CREATOR_SAVE_SECONDARY", "c1",
                        382L, "creator-web", "WEB", "911", "933", "CREATOR_SAVE_MEMBER"),
                new ContactDirectionCase(
                        41L, "SECONDARY_SAVE_CREATOR", "c2",
                        384L, "acc_384", "WEB", "933", "911", "MEMBER_SAVE_CREATOR"),
                new ContactDirectionCase(
                        41L, "SECONDARY_SAVE_ANCHOR", "c3",
                        384L, "acc_384", "WEB", "933", "922", "CREATOR_SAVE_MEMBER"),
                new ContactDirectionCase(
                        41L, "ANCHOR_SAVE_SECONDARY", "c4",
                        383L, "member-android", "ANDROID", "922", "933", "MEMBER_SAVE_CREATOR"));

        for (ContactDirectionCase testCase : cases) {
            ProtocolCommandOutbox row = outbox(testCase.commandId());
            row.setProtocolAccountId(testCase.protocolAccountId());
            row.setProtocolBackend(testCase.protocolBackend());
            JsonNode reference = objectMapper.valueToTree(new ProtocolNormalGroupCreationReference(
                    1L, 9L, 21L, testCase.memberId(), testCase.internalDirection(),
                    "CONTACT_PREPARE", "normal_group_creation"));

            JsonNode payload = hydrator.hydrate(row, reference);

            assertThat(payload.path("direction").asText())
                    .as(testCase.internalDirection())
                    .isEqualTo(testCase.protocolDirection());
            assertThat(payload.path("accountId").asLong())
                    .as(testCase.internalDirection())
                    .isEqualTo(testCase.actorAccountId());
            assertThat(payload.path("wsPhone").asText())
                    .as(testCase.internalDirection())
                    .isEqualTo(testCase.actorPhone());
            assertThat(payload.path("contact").asText())
                    .as(testCase.internalDirection())
                    .isEqualTo(testCase.contactPhone());
            assertThat(payload.path("name").asText())
                    .as(testCase.internalDirection())
                    .isEqualTo(testCase.contactPhone());
        }
    }

    private static SecondaryAdminWork secondaryAdmin(Long id, Long accountId, String phone) {
        return new SecondaryAdminWork(
                id, accountId, "acc_" + accountId, "WEB", phone,
                383L, "member-android", "ANDROID", "922",
                "SUCCESS", "SUCCESS", "SUCCESS", "SUCCESS",
                "c1", "c2", "c3", "c4", "PENDING", "PENDING", null);
    }

    private static ProtocolCommandOutbox outbox() {
        return outbox("cmd-settings");
    }

    private static ProtocolCommandOutbox outbox(String commandId) {
        ProtocolCommandOutbox row = new ProtocolCommandOutbox();
        row.setTenantId(1L);
        row.setCommandId(commandId);
        row.setCommandType("group.normal_creation.requested");
        row.setAggregateType("NORMAL_GROUP_CREATION_ITEM");
        row.setAggregateId(21L);
        row.setProtocolAccountId("creator-web");
        row.setProtocolBackend("WEB");
        return row;
    }

    private record ContactDirectionCase(
            Long memberId,
            String internalDirection,
            String commandId,
            Long actorAccountId,
            String protocolAccountId,
            String protocolBackend,
            String actorPhone,
            String contactPhone,
            String protocolDirection) {
    }
}
