package com.armada.account.takeover;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verifyNoInteractions;

import com.armada.account.mapper.AccountStateMapper;
import com.armada.account.service.AccountOnlineCommandService;
import com.armada.boot.config.MyBatisConfig;
import com.armada.shared.tenant.TenantContext;
import com.armada.testsupport.CreatorDeletionH2Schema;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.test.context.TestExecutionListeners;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;

/** 真实账号扫描 SQL、生产租户插件及补偿路由的 H2 回归。 */
@SpringJUnitConfig(AccountAutoTakeoverDispatcherH2Test.TestConfig.class)
@TestExecutionListeners(listeners = DependencyInjectionTestExecutionListener.class, inheritListeners = false)
class AccountAutoTakeoverDispatcherH2Test {

    private static final long NOW = 100_000L;
    private static final long STUCK_BEFORE = 70_000L;

    @Autowired private DataSource dataSource;
    @Autowired private AccountStateMapper states;
    @Autowired private PlatformTransactionManager transactionManager;
    private JdbcTemplate jdbc;
    private AccountAutoTakeoverProperties properties;

    @BeforeEach
    void setUp() {
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("DROP ALL OBJECTS");
        jdbc.execute(CreatorDeletionH2Schema.DDL);
        jdbc.execute("""
                CREATE TABLE account (
                  id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, deleted_at BIGINT,
                  creator_deletion_identity_phone VARCHAR(32)
                )
                """);
        jdbc.execute("""
                CREATE TABLE account_state (
                  id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, account_id BIGINT NOT NULL,
                  account_state INT, login_state INT, mute_status INT, desired_login_state INT,
                  last_state_sync_time BIGINT, updated_at BIGINT, UNIQUE(tenant_id, account_id)
                )
                """);
        jdbc.execute("""
                CREATE TABLE account_takeover_breaker (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL, account_id BIGINT NOT NULL, tripped_at BIGINT,
                  UNIQUE(tenant_id, account_id)
                )
                """);
        properties = new AccountAutoTakeoverProperties();
        TenantContext.set(99L);
    }

    @AfterEach
    void clearTenant() {
        TenantContext.clear();
    }

    @Test
    void scanFindsReplacedAndStuckTakingOverAccountsAcrossTenants() throws Exception {
        seed(101L, 1L, 6, 90_000L);
        seed(202L, 2L, 7, STUCK_BEFORE);
        seed(203L, 2L, 7, STUCK_BEFORE + 1L);

        assertThat(candidates(STUCK_BEFORE, 20)).containsExactly(
                new Candidate(2L, 202L, 7), new Candidate(1L, 101L, 6));
        assertThat(TenantContext.get()).isEqualTo(99L);
        assertThat(states.selectByAccountId(101L)).isNull();
    }

    @Test
    void scanExcludesDeletedMutedDesiredOfflineAndTrippedAccounts() throws Exception {
        for (long id = 101L; id <= 106L; id++) {
            seed(id, 1L, 6, 1_000L);
        }
        jdbc.update("UPDATE account SET deleted_at = 2000 WHERE id = 102");
        jdbc.update("UPDATE account_state SET mute_status = 1 WHERE account_id = 103");
        jdbc.update("UPDATE account_state SET desired_login_state = 2 WHERE account_id = 104");
        jdbc.update("INSERT INTO account_takeover_breaker(tenant_id, account_id, tripped_at) VALUES (1, 105, 2000)");
        jdbc.update("INSERT INTO account_takeover_breaker(tenant_id, account_id, tripped_at) VALUES (1, 106, NULL)");

        assertThat(candidates(STUCK_BEFORE, 20)).containsExactly(
                new Candidate(1L, 101L, 6), new Candidate(1L, 106L, 6));
    }

    @Test
    void scanExcludesEveryCreatorLifecycleByAccountOrGlobalIdentityAlias() throws Exception {
        seed(101L, 1L, 6, 1_000L);
        seed(102L, 1L, 6, 1_000L);
        seed(103L, 1L, 6, 1_000L);
        seed(104L, 1L, 6, 1_000L);
        seed(105L, 1L, 6, 1_000L);
        reserve(102L, 1L, "RESERVED", "owner-a");
        reserve(103L, 1L, "DELETING", "owner-b");
        reserve(104L, 1L, "DELETED", "owner-c");
        reserve(905L, 9L, "RESERVED", "owner-alias");
        jdbc.update("UPDATE account SET creator_deletion_identity_phone = 'owner-alias' WHERE id = 105");

        assertThat(candidates(STUCK_BEFORE, 20)).containsExactly(new Candidate(1L, 101L, 6));
    }

    @Test
    void scanRequiresOfflineAndOnlyTheTwoRecoverableLifecycleStates() throws Exception {
        for (int state = 1; state <= 9; state++) {
            seed(100L + state, 1L, state, 1_000L);
        }
        seed(201L, 2L, 6, 1_000L);
        seed(202L, 2L, 6, 1_000L);
        seed(203L, 2L, 6, 1_000L);
        jdbc.update("UPDATE account_state SET login_state = 1 WHERE account_id = 201");
        jdbc.update("UPDATE account_state SET login_state = 3 WHERE account_id = 202");
        jdbc.update("UPDATE account_state SET login_state = NULL WHERE account_id = 203");

        assertThat(candidates(STUCK_BEFORE, 20)).containsExactly(
                new Candidate(1L, 106L, 6), new Candidate(1L, 107L, 7));
    }

    @Test
    void scanAppliesBatchLimitAfterStableOldestFirstOrdering() throws Exception {
        seed(103L, 1L, 6, 1_000L);
        seed(101L, 1L, 6, 1_000L);
        seed(102L, 2L, 6, 2_000L);

        assertThat(candidates(STUCK_BEFORE, 2)).containsExactly(
                new Candidate(1L, 101L, 6), new Candidate(1L, 103L, 6));
    }

    @Test
    void scanDoesNotConfuseAnotherTenantsBreakerRow() throws Exception {
        seed(101L, 1L, 6, 1_000L);
        jdbc.update("INSERT INTO account_takeover_breaker(tenant_id, account_id, tripped_at) VALUES (2, 101, 2000)");

        assertThat(candidates(STUCK_BEFORE, 20)).containsExactly(new Candidate(1L, 101L, 6));
    }

    @Test
    void dispatcherRoutesByStateAndRestoresTenantAfterOneAccountFails() throws Exception {
        seed(101L, 1L, 6, 1_000L);
        seed(202L, 2L, 7, 2_000L);
        seed(303L, 3L, 6, 3_000L);
        List<String> calls = new ArrayList<>();
        AccountOnlineCommandService online = onlineRecorder(calls, 101L);

        assertThat(dispatch(online)).isEqualTo(3);
        assertThat(calls).containsExactly("autoTakeover:1:101", "reonlineForTakeover:2:202", "autoTakeover:3:303");
        assertThat(TenantContext.get()).isEqualTo(99L);
    }

    @Test
    void dispatcherUsesConfiguredBatchSizeAndStuckDelayWithoutLeakingTenant() throws Exception {
        seed(101L, 1L, 7, 59_999L);
        seed(202L, 2L, 7, 60_001L);
        seed(303L, 3L, 6, 90_000L);
        properties.getScan().setStuckTakingOverMs(40_000L);
        properties.getScan().setBatchSize(1);
        TenantContext.clear();
        List<String> calls = new ArrayList<>();

        assertThat(dispatch(onlineRecorder(calls, null))).isOne();
        assertThat(calls).containsExactly("reonlineForTakeover:1:101");
        assertThat(TenantContext.get()).isNull();
    }

    @Test
    void disabledDispatcherDoesNotReadCandidatesOrCallOnlineService() throws Exception {
        properties.setEnabled(false);
        jdbc.execute("DROP TABLE account_state");
        AccountOnlineCommandService online = mock(AccountOnlineCommandService.class);

        assertThat(dispatch(online)).isZero();
        verifyNoInteractions(online);
        assertThat(TenantContext.get()).isEqualTo(99L);
    }

    @Test
    void lockingReadUsesTenantIsolationAndExcludesCreatorDeletionInProgress() {
        seed(101L, 1L, 6, 1_000L);
        seed(102L, 1L, 6, 1_000L);
        seed(104L, 1L, 6, 1_000L);
        seed(203L, 2L, 6, 1_000L);
        jdbc.update("UPDATE account SET deleted_at = 2000 WHERE id = 104");
        reserve(102L, 1L, "DELETING", "owner-a");
        TenantContext.set(1L);

        new TransactionTemplate(transactionManager).executeWithoutResult(status -> {
            assertThat(states.lockTakeoverAccount(101L)).isEqualTo(101L);
            assertThat(states.lockTakeoverAccount(104L)).isNull();
            assertThat(states.lockTakeoverAccount(203L)).isNull();
            assertThat(states.selectByAccountIdForUpdate(101L).getAccountId()).isEqualTo(101L);
            assertThat(states.selectByAccountIdForUpdate(102L)).isNull();
            assertThat(states.selectByAccountIdForUpdate(203L)).isNull();
        });
    }

    @Test
    void lockingReadWaitsForUserOfflineTransactionAndSeesItsCommittedIntent() throws Exception {
        seed(101L, 1L, 6, 1_000L);
        TransactionTemplate transactions = new TransactionTemplate(transactionManager);
        CountDownLatch locked = new CountDownLatch(1);
        CountDownLatch release = new CountDownLatch(1);
        CountDownLatch attempted = new CountDownLatch(1);
        ExecutorService executor = Executors.newFixedThreadPool(2);
        try {
            Future<?> writer = executor.submit(() -> {
                TenantContext.set(1L);
                try {
                    transactions.executeWithoutResult(status -> {
                        assertThat(states.lockTakeoverAccount(101L)).isEqualTo(101L);
                        assertThat(states.selectByAccountIdForUpdate(101L)).isNotNull();
                        assertThat(states.updateDesiredLoginState(List.of(101L), 2, NOW)).isOne();
                        locked.countDown();
                        await(release);
                    });
                } finally {
                    TenantContext.clear();
                }
            });
            assertThat(locked.await(3, TimeUnit.SECONDS)).isTrue();
            Future<Integer> contender = executor.submit(() -> {
                TenantContext.set(1L);
                try {
                    return transactions.execute(status -> {
                        attempted.countDown();
                        assertThat(states.lockTakeoverAccount(101L)).isEqualTo(101L);
                        return states.selectByAccountIdForUpdate(101L).getDesiredLoginState();
                    });
                } finally {
                    TenantContext.clear();
                }
            });
            assertThat(attempted.await(3, TimeUnit.SECONDS)).isTrue();
            assertThatThrownBy(() -> contender.get(150, TimeUnit.MILLISECONDS)).isInstanceOf(TimeoutException.class);
            release.countDown();
            writer.get(3, TimeUnit.SECONDS);
            assertThat(contender.get(3, TimeUnit.SECONDS)).isEqualTo(2);
        } finally {
            release.countDown();
            executor.shutdownNow();
            assertThat(executor.awaitTermination(3, TimeUnit.SECONDS)).isTrue();
        }
    }

    private static void await(CountDownLatch latch) {
        try {
            if (!latch.await(3, TimeUnit.SECONDS)) {
                throw new IllegalStateException("等待锁测试释放信号超时");
            }
        } catch (InterruptedException error) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("锁测试被中断", error);
        }
    }

    private List<Candidate> candidates(long stuckBefore, int limit) {
        return states.selectAutoTakeoverCandidates(stuckBefore, limit).stream()
                .map(row -> new Candidate(row.tenantId(), row.accountId(), row.accountState())).toList();
    }

    private int dispatch(AccountOnlineCommandService online) {
        return new AccountAutoTakeoverDispatcher(states, online, properties).dispatchOnce(NOW);
    }

    private AccountOnlineCommandService onlineRecorder(List<String> calls, Long failingAccount) {
        return mock(AccountOnlineCommandService.class, invocation -> {
            String method = invocation.getMethod().getName();
            Long accountId = invocation.getArgument(0);
            calls.add(method + ":" + TenantContext.get() + ":" + accountId);
            if ("reonlineForTakeover".equals(method)) {
                assertThat((Object) invocation.getArgument(1)).isNull();
                assertThat((Object) invocation.getArgument(2)).isEqualTo("login_replaced_takeover");
            }
            if (accountId.equals(failingAccount)) {
                throw new IllegalStateException("expected unavailable proxy");
            }
            return null;
        });
    }

    private void seed(long accountId, long tenantId, int state, long syncedAt) {
        new TransactionTemplate(transactionManager).executeWithoutResult(status -> {
            jdbc.update("INSERT INTO account(id, tenant_id) VALUES (?, ?)", accountId, tenantId);
            jdbc.update("""
                    INSERT INTO account_state(id, tenant_id, account_id, account_state, login_state, last_state_sync_time)
                    VALUES (?, ?, ?, ?, 2, ?)
                    """, accountId, tenantId, accountId, state, syncedAt);
        });
    }

    private void reserve(long accountId, long tenantId, String lifecycle, String identity) {
        jdbc.update("""
                INSERT INTO account_creator_deletion(account_id, tenant_id, task_id, group_execution_id,
                  identity_hash, creator_phone, lifecycle)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """, accountId, tenantId, accountId, accountId, "hash-" + accountId, identity, lifecycle);
    }

    private record Candidate(Long tenantId, Long accountId, Integer accountState) { }

    @Configuration(proxyBeanMethods = false)
    @EnableTransactionManagement
    @Import(MyBatisConfig.class)
    static class TestConfig {

        @Bean
        DataSource dataSource() {
            JdbcDataSource source = new JdbcDataSource();
            source.setURL("jdbc:h2:mem:account_auto_takeover_dispatcher;MODE=MySQL;"
                    + "DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
            source.setUser("sa");
            source.setPassword("");
            return source;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(DataSource source, MybatisPlusInterceptor interceptor) throws Exception {
            MybatisConfiguration configuration = new MybatisConfiguration();
            configuration.setMapUnderscoreToCamelCase(true);
            MybatisSqlSessionFactoryBean factory = new MybatisSqlSessionFactoryBean();
            factory.setDataSource(source);
            factory.setConfiguration(configuration);
            factory.setPlugins(interceptor);
            factory.setMapperLocations(new ClassPathResource("mapper/account/AccountStateMapper.xml"));
            return factory.getObject();
        }

        @Bean
        SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory factory) {
            return new SqlSessionTemplate(factory);
        }

        @Bean
        AccountStateMapper stateMapper(SqlSessionTemplate sessions) {
            return sessions.getMapper(AccountStateMapper.class);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource source) {
            return new DataSourceTransactionManager(source);
        }
    }
}
