package com.armada.account.service.impl;

import static org.assertj.core.api.Assertions.assertThat;

import com.armada.account.mapper.AccountStateMapper;
import com.armada.account.model.enums.AccountOperationRestrictionStatus;
import com.armada.account.model.enums.AccountPullerRestrictionStatus;
import com.armada.account.service.AccountOperationRestrictionService;
import com.armada.boot.config.MyBatisConfig;
import com.armada.shared.tenant.TenantContext;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestExecutionListeners;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;

/** 统一账号操作限制写入、拉手汇总与跨租户到期恢复的真实 Mapper H2 测试。 */
@SpringJUnitConfig(AccountPullerRestrictionServiceH2Test.TestConfig.class)
@TestExecutionListeners(
        listeners = DependencyInjectionTestExecutionListener.class,
        inheritListeners = false)
class AccountPullerRestrictionServiceH2Test {

    private static final long DAY_MILLIS = 86_400_000L;

    @Autowired private DataSource dataSource;
    @Autowired private AccountOperationRestrictionService service;

    private JdbcTemplate jdbc;

    @BeforeEach
    void setUp() throws SQLException {
        jdbc = new JdbcTemplate(dataSource);
        execute("DROP ALL OBJECTS");
        execute("""
                CREATE TABLE account (
                  id BIGINT PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  account_group_id BIGINT,
                  deleted_at BIGINT
                )
                """);
        execute("""
                CREATE TABLE account_state (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  account_id BIGINT NOT NULL,
                  account_state TINYINT,
                  login_state TINYINT,
                  risk_status TINYINT,
                  risk_end_time BIGINT,
                  mute_status TINYINT,
                  cooldown_until BIGINT,
                  fallback_message_restriction_until BIGINT,
                  platform_message_restriction_until BIGINT,
                  platform_message_restriction_active TINYINT,
                  platform_message_restriction_reported_at BIGINT,
                  pulling_restriction_until BIGINT,
                  manual_restriction_cleared_at BIGINT,
                  restriction_reason_code VARCHAR(64),
                  restriction_reported_at BIGINT,
                  created_at BIGINT NOT NULL,
                  updated_at BIGINT NOT NULL,
                  UNIQUE (tenant_id, account_id)
                )
                """);
        seed(1L, 10L, 100L, 2, 1);
        seed(1L, 11L, 100L, 2, 1);
        seed(2L, 20L, 200L, 2, 1);
        TenantContext.set(1L);
    }

    @AfterEach
    void tearDown() {
        TenantContext.clear();
    }

    @Test
    void restrictionUsesTwentyFourHoursAndOlderFactCannotShortenDeadline() {
        assertThat(service.restrictPulling(10L, "rate_limited", 1_000L, 2_000L)).isTrue();
        assertThat(service.restrictPulling(10L, "older_reason", 500L, 2_000L)).isTrue();

        assertThat(status(1L, 10L))
                .isEqualTo(AccountOperationRestrictionStatus.PULLING_RESTRICTED.code());
        assertThat(until(1L, 10L)).isEqualTo(1_000L + DAY_MILLIS);
        assertThat(reason(1L, 10L)).isEqualTo("RATE_LIMITED");

        var restrictions = service.findPullerRestrictionsByAccountIds(
                java.util.List.of(10L, 11L));
        assertThat(restrictions.get(10L).status())
                .isEqualTo(AccountPullerRestrictionStatus.RESTRICTED.code());
        assertThat(restrictions.get(11L).status())
                .isEqualTo(AccountPullerRestrictionStatus.ALLOWED.code());
    }

    @Test
    void expiredLateFactDoesNotRestrictAndTenantIsolationPreventsForeignWrite() {
        assertThat(service.restrictPulling(
                10L, "RATE_LIMITED", 1_000L, DAY_MILLIS + 1_001L)).isFalse();
        assertThat(service.restrictPulling(
                20L, "RATE_LIMITED", 2_000L, 3_000L)).isFalse();

        assertThat(status(1L, 10L)).isNull();
        assertThat(status(2L, 20L)).isNull();
    }

    @Test
    void recoveryClearsOnlyDueRestrictionWithoutChangingLifecycleOrLoginState() {
        assertThat(service.restrictPulling(
                10L, "RATE_LIMITED", 1_000L, 2_000L)).isTrue();
        assertThat(service.restrictPulling(
                11L, "RATE_LIMITED", 2_000L, 2_000L)).isTrue();
        TenantContext.set(2L);
        assertThat(service.restrictPulling(
                20L, "RATE_LIMITED", 500L, 2_000L)).isTrue();
        TenantContext.clear();

        assertThat(service.restoreExpired(1_000L + DAY_MILLIS)).isEqualTo(2);

        assertThat(status(1L, 10L)).isNull();
        assertThat(status(1L, 11L))
                .isEqualTo(AccountOperationRestrictionStatus.PULLING_RESTRICTED.code());
        assertThat(status(2L, 20L)).isNull();
        assertThat(jdbc.queryForObject(
                "SELECT account_state FROM account_state WHERE tenant_id=1 AND account_id=10",
                Integer.class)).isEqualTo(2);
        assertThat(jdbc.queryForObject(
                "SELECT login_state FROM account_state WHERE tenant_id=1 AND account_id=10",
                Integer.class)).isEqualTo(1);
    }

    @Test
    void groupSummaryCountsRestrictedAccountsAndKeepsOverdueRowsRestrictedUntilScan() {
        assertThat(service.restrictPulling(
                10L, "RATE_LIMITED", 1_000L, 2_000L)).isTrue();
        assertThat(service.restrictPulling(
                11L, "RATE_LIMITED", 2_000L, 2_000L)).isTrue();

        var summary = service.summarizePullersByGroupId(
                100L, 1_000L + DAY_MILLIS + 1L);

        assertThat(summary.serverNow()).isEqualTo(1_000L + DAY_MILLIS + 1L);
        assertThat(summary.restrictedCount()).isEqualTo(2);
        assertThat(summary.nextRestrictionUntil()).isEqualTo(1_000L + DAY_MILLIS);
    }

    @Test
    void pullingRestrictionMergesWithMessageRestrictionAndKeepsLaterDeadline() {
        long messageUntil = 1_000L + DAY_MILLIS * 2;
        jdbc.update("""
                UPDATE account_state
                SET mute_status = 1, cooldown_until = ?,
                    fallback_message_restriction_until = ?,
                    restriction_reason_code = 'MESSAGE_RATE_LIMITED',
                    restriction_reported_at = 500
                WHERE tenant_id = 1 AND account_id = 10
                """, messageUntil, messageUntil);

        assertThat(service.restrictPulling(
                10L, "ACCOUNT_REACHOUT_RESTRICTED", 1_000L, 2_000L)).isTrue();

        assertThat(status(1L, 10L)).isEqualTo(
                AccountOperationRestrictionStatus
                        .MESSAGE_SENDING_AND_PULLING_RESTRICTED.code());
        assertThat(until(1L, 10L)).isEqualTo(messageUntil);
        assertThat(reason(1L, 10L)).isEqualTo("ACCOUNT_REACHOUT_RESTRICTED");
    }

    @Test
    void messageRestrictionUsesTheSameStatusAndDeadlineColumns() {
        assertThat(service.restrictMessageSending(
                11L, "CHAT_SUSPENDED", 3_000L, 4_000L)).isTrue();

        assertThat(status(1L, 11L)).isEqualTo(
                AccountOperationRestrictionStatus.MESSAGE_SENDING_RESTRICTED.code());
        assertThat(until(1L, 11L)).isEqualTo(3_000L + DAY_MILLIS);
        assertThat(reason(1L, 11L)).isEqualTo("CHAT_SUSPENDED");
        assertThat(service.findPullerRestrictionsByAccountIds(java.util.List.of(11L))
                .get(11L).status()).isEqualTo(AccountPullerRestrictionStatus.ALLOWED.code());
        assertThat(service.summarizePullersByGroupId(100L, 4_000L).restrictedCount()).isZero();
    }

    @Test
    void platformMessageRestrictionUsesExplicitDeadline() {
        long platformUntil = 9_999_000L;

        assertThat(service.restrictPlatformMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 3_000L, platformUntil, 4_000L))
                .isTrue();

        assertThat(status(1L, 11L)).isEqualTo(
                AccountOperationRestrictionStatus.MESSAGE_SENDING_RESTRICTED.code());
        assertThat(until(1L, 11L)).isEqualTo(platformUntil);
        assertThat(reason(1L, 11L)).isEqualTo("ACCOUNT_REACHOUT_RESTRICTED");
    }

    @Test
    void messageFailureCannotExtendAnActivePlatformDeadline() {
        long platformUntil = 20_000L;
        assertThat(service.restrictPlatformMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 3_000L, platformUntil, 4_000L))
                .isTrue();

        assertThat(service.restrictMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 5_000L, 6_000L)).isFalse();

        assertThat(until(1L, 11L)).isEqualTo(platformUntil);
        assertThat(sourceUntil("platform_message_restriction_until", 11L))
                .isEqualTo(platformUntil);
        assertThat(sourceUntil("fallback_message_restriction_until", 11L)).isNull();
    }

    @Test
    void delayedMessageFailureFromBeforePlatformDeadlineCannotRestartFallbackWindow() {
        assertThat(service.restrictPlatformMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 3_000L, 10_000L, 4_000L))
                .isTrue();

        assertThat(service.restrictMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 8_000L, 11_000L)).isFalse();
        assertThat(service.restrictMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 12_000L, 13_000L)).isTrue();

        assertThat(sourceUntil("fallback_message_restriction_until", 11L))
                .isEqualTo(12_000L + DAY_MILLIS);
    }

    @Test
    void expiredPlatformFactStillWatermarksDelayedPreCutoffMessageFailure() {
        assertThat(service.restrictPlatformMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 3_000L, 10_000L, 11_000L))
                .isTrue();

        assertThat(status(1L, 11L)).isNull();
        assertThat(sourceUntil("platform_message_restriction_until", 11L))
                .isEqualTo(10_000L);
        assertThat(service.restrictMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 8_000L, 11_000L)).isFalse();
        assertThat(sourceUntil("fallback_message_restriction_until", 11L)).isNull();
    }

    @Test
    void platformReleaseClearsOnlyPlatformMessageRestrictionAndKeepsPulling() {
        assertThat(service.restrictPulling(
                11L, "RATE_LIMITED", 3_000L, 4_000L)).isTrue();
        assertThat(service.restrictPlatformMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 4_000L, 30_000L, 5_000L))
                .isTrue();

        assertThat(service.clearPlatformMessageSending(11L, 6_000L, 7_000L)).isTrue();

        assertThat(status(1L, 11L)).isEqualTo(
                AccountOperationRestrictionStatus.PULLING_RESTRICTED.code());
        assertThat(until(1L, 11L)).isEqualTo(3_000L + DAY_MILLIS);
        assertThat(sourceUntil("platform_message_restriction_until", 11L)).isNull();
        assertThat(sourceUntil("pulling_restriction_until", 11L))
                .isEqualTo(3_000L + DAY_MILLIS);
    }

    @Test
    void stalePlatformReleaseCannotClearNewerActiveRestriction() {
        assertThat(service.restrictPlatformMessageSending(
                11L, "ACCOUNT_REACHOUT_RESTRICTED", 6_000L, 30_000L, 7_000L))
                .isTrue();

        assertThat(service.clearPlatformMessageSending(11L, 5_000L, 8_000L)).isFalse();

        assertThat(status(1L, 11L)).isEqualTo(
                AccountOperationRestrictionStatus.MESSAGE_SENDING_RESTRICTED.code());
        assertThat(sourceUntil("platform_message_restriction_until", 11L))
                .isEqualTo(30_000L);
    }

    @Test
    void manualClearRemovesBothBusinessRestrictionsAndWatermarksOldFacts() {
        long clearAt = 10_000L;
        jdbc.update("""
                UPDATE account_state
                SET risk_status = 2, risk_end_time = 99_000
                WHERE tenant_id = 1 AND account_id = 10
                """);
        assertThat(service.restrictPulling(
                10L, "RATE_LIMITED", 3_000L, 4_000L)).isTrue();
        assertThat(service.restrictPlatformMessageSending(
                10L, "ACCOUNT_REACHOUT_RESTRICTED", 4_000L, 80_000L, 5_000L))
                .isTrue();

        var result = service.clearOperationRestrictionsManually(
                java.util.List.of(10L, 20L, 10L), clearAt);

        assertThat(result.requested()).isEqualTo(2);
        assertThat(result.cleared()).isEqualTo(1);
        assertThat(status(1L, 10L)).isNull();
        assertThat(until(1L, 10L)).isNull();
        assertThat(sourceUntil("fallback_message_restriction_until", 10L)).isNull();
        assertThat(sourceUntil("platform_message_restriction_until", 10L)).isNull();
        assertThat(sourceUntil("pulling_restriction_until", 10L)).isNull();
        assertThat(sourceUntil("manual_restriction_cleared_at", 10L)).isEqualTo(clearAt);
        assertThat(jdbc.queryForObject("""
                SELECT risk_status FROM account_state
                WHERE tenant_id = 1 AND account_id = 10
                """, Integer.class)).isEqualTo(2);
        assertThat(jdbc.queryForObject("""
                SELECT risk_end_time FROM account_state
                WHERE tenant_id = 1 AND account_id = 10
                """, Long.class)).isEqualTo(99_000L);

        assertThat(service.restrictPulling(
                10L, "OLD_PULLING", 9_000L, 11_000L)).isFalse();
        assertThat(service.restrictMessageSending(
                10L, "OLD_MESSAGE", 9_500L, 11_000L)).isFalse();
        assertThat(service.restrictPlatformMessageSending(
                10L, "OLD_PLATFORM", 9_000L, 90_000L, 11_000L)).isFalse();
        assertThat(service.restrictPulling(
                10L, "NEW_PULLING", 12_000L, 13_000L)).isTrue();
        assertThat(service.restrictMessageSending(
                10L, "NEW_MESSAGE", 12_001L, 13_000L)).isTrue();
        assertThat(status(1L, 10L)).isEqualTo(
                AccountOperationRestrictionStatus
                        .MESSAGE_SENDING_AND_PULLING_RESTRICTED.code());
    }

    @Test
    void recoveryDrainsMoreThanOneFiveHundredRowBatchInOneRun() {
        for (long accountId = 1_000L; accountId <= 1_500L; accountId++) {
            seed(1L, accountId, 100L, 2, 1);
            assertThat(service.restrictPulling(
                    accountId, "RATE_LIMITED", 1_000L, 2_000L)).isTrue();
        }

        assertThat(service.restoreExpired(1_000L + DAY_MILLIS)).isEqualTo(501);
        assertThat(jdbc.queryForObject(
                "SELECT COUNT(*) FROM account_state WHERE mute_status IS NOT NULL",
                Integer.class)).isZero();
    }

    private void seed(
            long tenantId, long accountId, long groupId, int accountState, int loginState) {
        jdbc.update("INSERT INTO account (id, tenant_id, account_group_id) VALUES (?, ?, ?)",
                accountId, tenantId, groupId);
        jdbc.update("""
                INSERT INTO account_state (
                  tenant_id, account_id, account_state, login_state, created_at, updated_at
                ) VALUES (?, ?, ?, ?, 100, 100)
                """, tenantId, accountId, accountState, loginState);
    }

    private Integer status(long tenantId, long accountId) {
        return jdbc.queryForObject("""
                SELECT mute_status FROM account_state
                WHERE tenant_id=? AND account_id=?
                """, Integer.class, tenantId, accountId);
    }

    private Long until(long tenantId, long accountId) {
        return jdbc.queryForObject("""
                SELECT cooldown_until FROM account_state
                WHERE tenant_id=? AND account_id=?
                """, Long.class, tenantId, accountId);
    }

    private String reason(long tenantId, long accountId) {
        return jdbc.queryForObject("""
                SELECT restriction_reason_code FROM account_state
                WHERE tenant_id=? AND account_id=?
                """, String.class, tenantId, accountId);
    }

    private Long sourceUntil(String column, long accountId) {
        return jdbc.queryForObject(
                "SELECT " + column + " FROM account_state WHERE tenant_id=1 AND account_id=?",
                Long.class, accountId);
    }

    private void execute(String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    @Configuration(proxyBeanMethods = false)
    @Import(MyBatisConfig.class)
    static class TestConfig {

        @Bean
        DataSource dataSource() {
            JdbcDataSource h2 = new JdbcDataSource();
            h2.setURL("jdbc:h2:mem:puller_restriction_test;MODE=MySQL;"
                    + "DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
            h2.setUser("sa");
            h2.setPassword("");
            return h2;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(
                DataSource dataSource,
                MybatisPlusInterceptor interceptor) throws Exception {
            MybatisConfiguration configuration = new MybatisConfiguration();
            configuration.setMapUnderscoreToCamelCase(true);
            MybatisSqlSessionFactoryBean factory = new MybatisSqlSessionFactoryBean();
            factory.setDataSource(dataSource);
            factory.setConfiguration(configuration);
            factory.setPlugins(interceptor);
            factory.setMapperLocations(new ClassPathResource(
                    "mapper/account/AccountStateMapper.xml"));
            return factory.getObject();
        }

        @Bean
        SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory factory) {
            return new SqlSessionTemplate(factory);
        }

        @Bean
        AccountStateMapper stateMapper(SqlSessionTemplate template) {
            return template.getMapper(AccountStateMapper.class);
        }

        @Bean
        AccountOperationRestrictionService restrictionService(AccountStateMapper mapper) {
            return new AccountOperationRestrictionServiceImpl(mapper);
        }
    }
}
