package com.armada.account.service.impl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import com.armada.account.mapper.AccountMapper;
import com.armada.account.mapper.AccountStateMapper;
import com.armada.account.model.entity.Account;
import com.armada.account.model.entity.AccountLoginStateCode;
import com.armada.account.service.AccountStateChangedEvent;
import com.armada.account.service.AccountStateEventService;
import com.armada.account.state.AccountStateChangedSideEffect;
import com.armada.boot.config.MyBatisConfig;
import com.armada.resource.service.IpProxyService;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;
import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.test.context.TestExecutionListeners;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;

/** 账号状态事件时间水位与行锁的 H2 并发回归测试。 */
@SpringJUnitConfig(AccountStateEventServiceConcurrencyH2Test.TestConfig.class)
@TestExecutionListeners(
        listeners = DependencyInjectionTestExecutionListener.class,
        inheritListeners = false)
class AccountStateEventServiceConcurrencyH2Test {

    private static final long ACCOUNT_ID = 100L;
    private static final String PROTOCOL_ACCOUNT_ID = "acc_8613800138000";

    @Autowired private DataSource dataSource;
    @Autowired private AccountMapper accountMapper;
    @Autowired private IpProxyService ipProxyService;
    @Autowired private AccountStateChangedSideEffect sideEffect;
    @Autowired private AccountStateEventService service;
    @Autowired private PlatformTransactionManager transactionManager;

    @BeforeEach
    void setUp() throws SQLException {
        reset(accountMapper, ipProxyService, sideEffect);
        execute("DROP ALL OBJECTS");
        execute("""
                CREATE TABLE account_state (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  account_id BIGINT NOT NULL,
                  account_state TINYINT,
                  login_state TINYINT,
                  block_reason VARCHAR(255),
                  state_source VARCHAR(64),
                  last_state_sync_time BIGINT,
                  invalidated_at BIGINT,
                  created_at BIGINT NOT NULL,
                  updated_at BIGINT NOT NULL,
                  UNIQUE (tenant_id, account_id)
                )
                """);
        execute("""
                INSERT INTO account_state (
                  tenant_id, account_id, account_state, login_state,
                  state_source, last_state_sync_time, created_at, updated_at
                ) VALUES (1, 100, 2, 2, 'INITIAL', 1000, 1000, 1000)
                """);
        Account account = new Account();
        account.setId(ACCOUNT_ID);
        account.setProtocolAccountId(PROTOCOL_ACCOUNT_ID);
        when(accountMapper.selectActiveById(ACCOUNT_ID)).thenReturn(account);
    }

    @Test
    void newerOnlineCommitPreventsWaitingOlderOfflineFromOverwritingState() throws Exception {
        CountDownLatch newerApplied = new CountDownLatch(1);
        CountDownLatch releaseNewer = new CountDownLatch(1);
        CountDownLatch olderAttempting = new CountDownLatch(1);
        CountDownLatch olderFinished = new CountDownLatch(1);
        AtomicReference<Boolean> olderResult = new AtomicReference<>();
        ExecutorService executor = Executors.newFixedThreadPool(2);
        TransactionTemplate transactions = new TransactionTemplate(transactionManager);
        try {
            Future<?> newer = executor.submit(() -> transactions.executeWithoutResult(status -> {
                assertThat(service.applyStateChanged(event("OFFLINE", "ONLINE", 3_000L)))
                        .isTrue();
                newerApplied.countDown();
                await(releaseNewer);
            }));
            if (!newerApplied.await(2, TimeUnit.SECONDS)) {
                newer.get(2, TimeUnit.SECONDS);
                throw new IllegalStateException("较新 ONLINE 事件未进入持锁阶段");
            }

            Future<?> older = executor.submit(() -> {
                try {
                    transactions.executeWithoutResult(status -> {
                        olderAttempting.countDown();
                        olderResult.set(service.applyStateChanged(
                                event("ONLINE", "OFFLINE", 2_000L)));
                    });
                } finally {
                    olderFinished.countDown();
                }
            });
            assertThat(olderAttempting.await(2, TimeUnit.SECONDS)).isTrue();
            assertThat(olderFinished.await(200, TimeUnit.MILLISECONDS)).isFalse();

            releaseNewer.countDown();
            newer.get(2, TimeUnit.SECONDS);
            older.get(2, TimeUnit.SECONDS);

            JdbcTemplate jdbc = new JdbcTemplate(dataSource);
            assertThat(jdbc.queryForObject(
                    "SELECT login_state FROM account_state WHERE account_id = 100",
                    Integer.class)).isEqualTo(AccountLoginStateCode.ONLINE);
            assertThat(jdbc.queryForObject(
                    "SELECT last_state_sync_time FROM account_state WHERE account_id = 100",
                    Long.class)).isEqualTo(3_000L);
            assertThat(olderResult.get()).isFalse();
            verifyNoInteractions(ipProxyService);
        } finally {
            releaseNewer.countDown();
            executor.shutdownNow();
        }
    }

    @Test
    void sameTimestampOnlineFirstPreventsDerivedOfflineFromOverwritingState() throws Exception {
        CountDownLatch onlineApplied = new CountDownLatch(1);
        CountDownLatch releaseOnline = new CountDownLatch(1);
        CountDownLatch offlineAttempting = new CountDownLatch(1);
        CountDownLatch offlineFinished = new CountDownLatch(1);
        AtomicReference<Boolean> offlineResult = new AtomicReference<>();
        ExecutorService executor = Executors.newFixedThreadPool(2);
        TransactionTemplate transactions = new TransactionTemplate(transactionManager);
        try {
            Future<?> online = executor.submit(() -> transactions.executeWithoutResult(status -> {
                assertThat(service.applyStateChanged(event("OFFLINE", "ONLINE", 3_000L)))
                        .isTrue();
                onlineApplied.countDown();
                await(releaseOnline);
            }));
            if (!onlineApplied.await(2, TimeUnit.SECONDS)) {
                online.get(2, TimeUnit.SECONDS);
                throw new IllegalStateException("同水位 ONLINE 事件未进入持锁阶段");
            }

            Future<?> offline = executor.submit(() -> {
                try {
                    transactions.executeWithoutResult(status -> {
                        offlineAttempting.countDown();
                        offlineResult.set(service.applyStateChanged(normalGroupOfflineEvent(3_000L)));
                    });
                } finally {
                    offlineFinished.countDown();
                }
            });
            assertThat(offlineAttempting.await(2, TimeUnit.SECONDS)).isTrue();
            assertThat(offlineFinished.await(200, TimeUnit.MILLISECONDS)).isFalse();

            releaseOnline.countDown();
            online.get(2, TimeUnit.SECONDS);
            offline.get(2, TimeUnit.SECONDS);

            assertOnlineAt(3_000L);
            assertThat(offlineResult.get()).isFalse();
            verifyNoInteractions(ipProxyService);
            assertNoNormalGroupSideEffects();
        } finally {
            releaseOnline.countDown();
            executor.shutdownNow();
        }
    }

    @Test
    void sameTimestampDerivedOfflineFirstStillAllowsOnlineToWinWithoutOfflineSideEffects()
            throws Exception {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.update("UPDATE account_state SET login_state = ?, last_state_sync_time = 1000 "
                        + "WHERE tenant_id = 1 AND account_id = 100",
                AccountLoginStateCode.ONLINE);

        CountDownLatch offlineApplied = new CountDownLatch(1);
        CountDownLatch releaseOffline = new CountDownLatch(1);
        CountDownLatch onlineAttempting = new CountDownLatch(1);
        CountDownLatch onlineFinished = new CountDownLatch(1);
        ExecutorService executor = Executors.newFixedThreadPool(2);
        TransactionTemplate transactions = new TransactionTemplate(transactionManager);
        try {
            Future<?> offline = executor.submit(() -> transactions.executeWithoutResult(status -> {
                assertThat(service.applyStateChanged(normalGroupOfflineEvent(3_000L))).isTrue();
                offlineApplied.countDown();
                await(releaseOffline);
            }));
            if (!offlineApplied.await(2, TimeUnit.SECONDS)) {
                offline.get(2, TimeUnit.SECONDS);
                throw new IllegalStateException("同水位派生 OFFLINE 未进入持锁阶段");
            }

            Future<?> online = executor.submit(() -> {
                try {
                    transactions.executeWithoutResult(status -> {
                        onlineAttempting.countDown();
                        assertThat(service.applyStateChanged(event("OFFLINE", "ONLINE", 3_000L)))
                                .isTrue();
                    });
                } finally {
                    onlineFinished.countDown();
                }
            });
            assertThat(onlineAttempting.await(2, TimeUnit.SECONDS)).isTrue();
            assertThat(onlineFinished.await(200, TimeUnit.MILLISECONDS)).isFalse();

            releaseOffline.countDown();
            offline.get(2, TimeUnit.SECONDS);
            online.get(2, TimeUnit.SECONDS);

            assertOnlineAt(3_000L);
            verifyNoInteractions(ipProxyService);
            assertNoNormalGroupSideEffects();
        } finally {
            releaseOffline.countDown();
            executor.shutdownNow();
        }
    }

    private static AccountStateChangedEvent event(String from, String to, long occurredAt) {
        return new AccountStateChangedEvent(
                1L, ACCOUNT_ID, PROTOCOL_ACCOUNT_ID,
                from, to, occurredAt, to, null, "test", null);
    }

    private static AccountStateChangedEvent normalGroupOfflineEvent(long occurredAt) {
        return new AccountStateChangedEvent(
                1L, ACCOUNT_ID, PROTOCOL_ACCOUNT_ID,
                "ONLINE", "OFFLINE", occurredAt,
                "NORMAL_GROUP_ACCOUNT_NOT_ONLINE", null, "normal_group_creation", null);
    }

    private void assertOnlineAt(long occurredAt) {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        assertThat(jdbc.queryForObject(
                "SELECT login_state FROM account_state WHERE account_id = 100",
                Integer.class)).isEqualTo(AccountLoginStateCode.ONLINE);
        assertThat(jdbc.queryForObject(
                "SELECT last_state_sync_time FROM account_state WHERE account_id = 100",
                Long.class)).isEqualTo(occurredAt);
    }

    private void assertNoNormalGroupSideEffects() {
        verify(sideEffect, never()).afterStateChanged(
                org.mockito.ArgumentMatchers.any(Account.class),
                org.mockito.ArgumentMatchers.argThat(event ->
                        "normal_group_creation".equals(event.source())),
                org.mockito.ArgumentMatchers.anyLong());
    }

    private static void await(CountDownLatch latch) {
        try {
            if (!latch.await(2, TimeUnit.SECONDS)) {
                throw new IllegalStateException("等待并发测试信号超时");
            }
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("并发测试被中断", ex);
        }
    }

    private void execute(String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    @Configuration(proxyBeanMethods = false)
    @EnableTransactionManagement
    @Import(MyBatisConfig.class)
    static class TestConfig {

        @Bean
        DataSource dataSource() {
            JdbcDataSource h2 = new JdbcDataSource();
            h2.setURL("jdbc:h2:mem:account_state_event_concurrency_test;MODE=MySQL;"
                    + "DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=5000");
            h2.setUser("sa");
            h2.setPassword("");
            return h2;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(
                DataSource dataSource,
                MybatisPlusInterceptor interceptor) throws Exception {
            MybatisConfiguration configuration = new MybatisConfiguration();
            configuration.setMapUnderscoreToCamelCase(true);
            MybatisSqlSessionFactoryBean factory = new MybatisSqlSessionFactoryBean();
            factory.setDataSource(dataSource);
            factory.setConfiguration(configuration);
            factory.setPlugins(interceptor);
            factory.setMapperLocations(new ClassPathResource(
                    "mapper/account/AccountStateMapper.xml"));
            return factory.getObject();
        }

        @Bean
        SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory factory) {
            return new SqlSessionTemplate(factory);
        }

        @Bean
        AccountStateMapper stateMapper(SqlSessionTemplate template) {
            return template.getMapper(AccountStateMapper.class);
        }

        @Bean
        AccountMapper accountMapper() {
            return Mockito.mock(AccountMapper.class);
        }

        @Bean
        IpProxyService ipProxyService() {
            return Mockito.mock(IpProxyService.class);
        }

        @Bean
        AccountStateChangedSideEffect accountStateChangedSideEffect() {
            return Mockito.mock(AccountStateChangedSideEffect.class);
        }

        @Bean
        AccountStateEventService accountStateEventService(
                AccountMapper accountMapper,
                AccountStateMapper stateMapper,
                IpProxyService ipProxyService,
                AccountStateChangedSideEffect sideEffect) {
            return new AccountStateEventServiceImpl(
                    accountMapper, stateMapper, ipProxyService, List.of(sideEffect));
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }
    }
}
