package com.armada.account.service.impl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import com.armada.account.mapper.AccountMapper;
import com.armada.account.mapper.AccountOnlineAttemptLogMapper;
import com.armada.account.mapper.AccountStateMapper;
import com.armada.account.model.entity.Account;
import com.armada.account.model.entity.AccountLoginStateCode;
import com.armada.account.service.AccountStateChangedEvent;
import com.armada.account.service.AccountOnlineAttemptLogService;
import com.armada.account.service.AccountOnlineCommandService;
import com.armada.account.recovery.ProxyFailedRecoveryCoordinator;
import com.armada.account.recovery.ProxyFailedRecoveryDispatcher;
import com.armada.account.state.ProxyFailureContextSideEffect;
import com.armada.platform.protocol.service.ProtocolCommandOutboxService;
import com.armada.shared.tenant.TenantContext;
import com.armada.account.service.AccountStateEventService;
import com.armada.account.state.AccountStateChangedSideEffect;
import com.armada.boot.config.MyBatisConfig;
import com.armada.resource.service.IpProxyService;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.test.context.TestExecutionListeners;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.test.context.support.DependencyInjectionTestExecutionListener;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;

/** 账号状态事件普通读取、时间水位与事务写入的 H2 回归测试。 */
@SpringJUnitConfig(AccountStateEventServiceConcurrencyH2Test.TestConfig.class)
@TestExecutionListeners(
        listeners = DependencyInjectionTestExecutionListener.class,
        inheritListeners = false)
class AccountStateEventServiceConcurrencyH2Test {

    private static final long ACCOUNT_ID = 100L;
    private static final String PROTOCOL_ACCOUNT_ID = "acc_8613800138000";

    @Autowired private DataSource dataSource;
    @Autowired private AccountMapper accountMapper;
    @Autowired private IpProxyService ipProxyService;
    @Autowired @Qualifier("accountStateChangedSideEffect") private AccountStateChangedSideEffect sideEffect;
    @Autowired private AccountStateMapper stateMapper;
    @Autowired private AccountOnlineAttemptLogService attemptLogService;
    @Autowired private AccountStateEventService service;
    @Autowired private PlatformTransactionManager transactionManager;

    @BeforeEach
    void setUp() throws SQLException {
        reset(accountMapper, ipProxyService, sideEffect);
        execute("DROP ALL OBJECTS");
        execute("""
                CREATE TABLE account_state (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL,
                  account_id BIGINT NOT NULL,
                  account_state TINYINT,
                  login_state TINYINT,
                  desired_login_state TINYINT,
                  block_reason VARCHAR(255),
                  state_source VARCHAR(64),
                  last_state_sync_time BIGINT,
                  invalidated_at BIGINT,
                  created_at BIGINT NOT NULL,
                  updated_at BIGINT NOT NULL,
                  UNIQUE (tenant_id, account_id)
                )
                """);
        execute("""
                INSERT INTO account_state (
                  tenant_id, account_id, account_state, login_state,
                  state_source, last_state_sync_time, created_at, updated_at
                ) VALUES (1, 100, 2, 2, 'INITIAL', 1000, 1000, 1000)
                """);
        execute("CREATE TABLE account (id BIGINT PRIMARY KEY, tenant_id BIGINT, deleted_at BIGINT)");
        execute("INSERT INTO account VALUES (100, 1, NULL)");
        execute("""
                CREATE TABLE account_online_attempt_log (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tenant_id BIGINT NOT NULL, account_id BIGINT NOT NULL,
                  protocol_account_id VARCHAR(128), online_attempt_id VARCHAR(128) NOT NULL,
                  previous_online_attempt_id VARCHAR(128), command_id VARCHAR(128), batch_id VARCHAR(128),
                  proxy_id BIGINT, source VARCHAR(64), from_state VARCHAR(64), to_state VARCHAR(64),
                  diagnosis_code VARCHAR(128), diagnosis_class VARCHAR(64), raw_code INT,
                  raw_reason VARCHAR(512), recoverability VARCHAR(64), action_taken VARCHAR(64),
                  worker_id VARCHAR(128), evidence_json VARCHAR(4096),
                  occurred_at TIMESTAMP(3), created_at TIMESTAMP(3)
                )
                """);
        Account account = new Account();
        account.setId(ACCOUNT_ID);
        account.setProtocolAccountId(PROTOCOL_ACCOUNT_ID);
        when(accountMapper.selectActiveById(ACCOUNT_ID)).thenReturn(account);
    }

    @Test
    void androidFailureContextCommitsWithStateAndSurvivesMissingDiagnosisAndReallocationFailure() {
        AccountStateChangedEvent failure = proxyFailure("oa_failed", 2_000L, null);
        assertThat(service.applyStateChanged(failure)).isTrue();
        assertThat(service.applyStateChanged(failure)).isTrue();
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM account_online_attempt_log", Integer.class)).isOne();
        TenantContext.set(1L);
        try {
            assertThat(attemptLogService.proxyFailureAt(ACCOUNT_ID, 1_999L)).isNull();
            assertThat(attemptLogService.proxyFailureAt(ACCOUNT_ID, 2_000L).onlineAttemptId()).isEqualTo("oa_failed");
            AccountOnlineCommandService online = Mockito.mock(AccountOnlineCommandService.class);
            ProtocolCommandOutboxService outbox = Mockito.mock(ProtocolCommandOutboxService.class);
            when(outbox.findOnlineAttemptProxyId(ACCOUNT_ID, "oa_failed")).thenReturn(Optional.of(7L));
            when(ipProxyService.markFailedProxyUnavailable(ACCOUNT_ID, 7L, 2_000L)).thenReturn(true);
            when(online.reonlineAfterProxyFailure(ACCOUNT_ID, "oa_failed", 7L, 2_000L))
                    .thenThrow(new IllegalStateException("no idle proxy")).thenReturn(null);
            ProxyFailedRecoveryDispatcher dispatcher = new ProxyFailedRecoveryDispatcher(
                    stateMapper, attemptLogService, new ProxyFailedRecoveryCoordinator(ipProxyService, online, outbox));
            assertThat(dispatcher.dispatchOnce()).isOne();
            // 重建 dispatcher 模拟进程内存丢失，仍能从已提交状态和失败上下文继续同一尝试。
            assertThat(new ProxyFailedRecoveryDispatcher(stateMapper, attemptLogService,
                    new ProxyFailedRecoveryCoordinator(ipProxyService, online, outbox)).dispatchOnce()).isOne();
            verify(online, Mockito.times(2)).reonlineAfterProxyFailure(ACCOUNT_ID, "oa_failed", 7L, 2_000L);
            TenantContext.set(2L);
            assertThat(attemptLogService.proxyFailureAt(ACCOUNT_ID, 2_000L)).isNull();
        } finally {
            TenantContext.clear();
        }
    }

    @Test
    void failedContextInsertRollsBackStateAndStaleFailureDoesNotWriteContext() {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("ALTER TABLE account_online_attempt_log ADD CHECK (diagnosis_code <> 'PROXY_FAILED')");
        assertThatThrownBy(() -> service.applyStateChanged(proxyFailure("oa_failed", 2_000L, 7L)))
                .isInstanceOf(RuntimeException.class);
        assertThat(jdbc.queryForObject("SELECT last_state_sync_time FROM account_state", Long.class))
                .isEqualTo(1_000L);
        assertThat(service.applyStateChanged(proxyFailure("oa_old", 999L, 6L))).isFalse();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM account_online_attempt_log", Integer.class)).isZero();
    }

    @Test
    void legacyFailureWithoutAttemptStillCommitsItsState() {
        assertThat(service.applyStateChanged(proxyFailure(null, 2_000L, null))).isTrue();
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        assertThat(jdbc.queryForObject("SELECT last_state_sync_time FROM account_state", Long.class))
                .isEqualTo(2_000L);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM account_online_attempt_log", Integer.class)).isZero();
    }

    @Test
    void recoveryClaimRequiresExactFailureWatermarkAndTenant() {
        assertThat(service.applyStateChanged(proxyFailure("oa_failed", 2_000L, 7L))).isTrue();
        TenantContext.set(1L);
        try {
            assertThat(attemptLogService.proxyFailureAt(ACCOUNT_ID, 2_000L).proxyId()).isEqualTo(7L);
            assertThat(stateMapper.claimProxyFailedReonline(ACCOUNT_ID, 1_999L, 3_000L)).isZero();
            TenantContext.set(2L);
            assertThat(stateMapper.claimProxyFailedReonline(ACCOUNT_ID, 2_000L, 3_000L)).isZero();
            TenantContext.set(1L);
            assertThat(stateMapper.claimProxyFailedReonline(ACCOUNT_ID, 2_000L, 3_000L)).isOne();
            assertThat(stateMapper.claimProxyFailedReonline(ACCOUNT_ID, 2_000L, 3_001L)).isZero();
        } finally {
            TenantContext.clear();
        }
    }

    private static AccountStateChangedEvent proxyFailure(String attempt, long occurredAt, Long proxyId) {
        return new AccountStateChangedEvent(1L, ACCOUNT_ID, PROTOCOL_ACCOUNT_ID, "VERIFYING", "PROXY_FAILED",
                occurredAt, "PROXY_FAILED", 302, "batch_online", attempt, proxyId);
    }

    @Test
    void staleEventReadsCommittedStateWithoutWaitingForAnotherWriter() throws Exception {
        assertThat(service.applyStateChanged(event("OFFLINE", "ONLINE", 3_000L))).isTrue();
        reset(ipProxyService, sideEffect);
        CountDownLatch writerApplied = new CountDownLatch(1);
        CountDownLatch releaseWriter = new CountDownLatch(1);
        ExecutorService executor = Executors.newFixedThreadPool(2);
        TransactionTemplate transactions = new TransactionTemplate(transactionManager);
        try {
            Future<?> writer = executor.submit(() -> transactions.executeWithoutResult(status -> {
                new JdbcTemplate(dataSource).update(
                        "UPDATE account_state SET updated_at = 4000 WHERE tenant_id = 1 AND account_id = 100");
                writerApplied.countDown();
                await(releaseWriter);
            }));
            assertThat(writerApplied.await(2, TimeUnit.SECONDS)).isTrue();
            Future<Boolean> stale = executor.submit(() ->
                    service.applyStateChanged(event("ONLINE", "OFFLINE", 2_000L)));
            // 写事务尚未提交，普通查询应读取已提交水位并直接丢弃旧事件，而非等待行锁。
            assertThat(stale.get(1, TimeUnit.SECONDS)).isFalse();
            verifyNoInteractions(ipProxyService, sideEffect);
            releaseWriter.countDown();
            writer.get(2, TimeUnit.SECONDS);
            assertOnlineAt(3_000L);
        } finally {
            releaseWriter.countDown();
            executor.shutdownNow();
            assertThat(executor.awaitTermination(3, TimeUnit.SECONDS)).isTrue();
        }
    }

    @Test
    void committedNewerOnlinePreventsLaterOlderOfflineFromOverwritingState() {
        assertThat(service.applyStateChanged(event("OFFLINE", "ONLINE", 3_000L))).isTrue();
        assertThat(service.applyStateChanged(event("ONLINE", "OFFLINE", 2_000L))).isFalse();
        assertOnlineAt(3_000L);
        verifyNoInteractions(ipProxyService);
    }

    @Test
    void committedSameTimestampOnlinePreventsLaterDerivedOfflineFromOverwritingState() {
        assertThat(service.applyStateChanged(event("OFFLINE", "ONLINE", 3_000L))).isTrue();
        assertThat(service.applyStateChanged(normalGroupOfflineEvent(3_000L))).isFalse();
        assertOnlineAt(3_000L);
        verifyNoInteractions(ipProxyService);
        assertNoNormalGroupSideEffects();
    }

    @Test
    void sameTimestampDerivedOfflineFirstStillAllowsOnlineToWinWithoutOfflineSideEffects()
            throws Exception {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.update("UPDATE account_state SET login_state = ?, last_state_sync_time = 1000 "
                        + "WHERE tenant_id = 1 AND account_id = 100",
                AccountLoginStateCode.ONLINE);

        CountDownLatch offlineApplied = new CountDownLatch(1);
        CountDownLatch releaseOffline = new CountDownLatch(1);
        CountDownLatch onlineAttempting = new CountDownLatch(1);
        CountDownLatch onlineFinished = new CountDownLatch(1);
        ExecutorService executor = Executors.newFixedThreadPool(2);
        TransactionTemplate transactions = new TransactionTemplate(transactionManager);
        try {
            Future<?> offline = executor.submit(() -> transactions.executeWithoutResult(status -> {
                assertThat(service.applyStateChanged(normalGroupOfflineEvent(3_000L))).isTrue();
                offlineApplied.countDown();
                await(releaseOffline);
            }));
            if (!offlineApplied.await(2, TimeUnit.SECONDS)) {
                offline.get(2, TimeUnit.SECONDS);
                throw new IllegalStateException("同水位派生 OFFLINE 未进入持锁阶段");
            }

            Future<?> online = executor.submit(() -> {
                try {
                    transactions.executeWithoutResult(status -> {
                        onlineAttempting.countDown();
                        assertThat(service.applyStateChanged(event("OFFLINE", "ONLINE", 3_000L)))
                                .isTrue();
                    });
                } finally {
                    onlineFinished.countDown();
                }
            });
            assertThat(onlineAttempting.await(2, TimeUnit.SECONDS)).isTrue();
            assertThat(onlineFinished.await(200, TimeUnit.MILLISECONDS)).isFalse();

            releaseOffline.countDown();
            offline.get(2, TimeUnit.SECONDS);
            online.get(2, TimeUnit.SECONDS);

            assertOnlineAt(3_000L);
            verifyNoInteractions(ipProxyService);
            assertNoNormalGroupSideEffects();
        } finally {
            releaseOffline.countDown();
            executor.shutdownNow();
        }
    }

    private static AccountStateChangedEvent event(String from, String to, long occurredAt) {
        return new AccountStateChangedEvent(
                1L, ACCOUNT_ID, PROTOCOL_ACCOUNT_ID,
                from, to, occurredAt, to, null, "test", null, null);
    }

    private static AccountStateChangedEvent normalGroupOfflineEvent(long occurredAt) {
        return new AccountStateChangedEvent(
                1L, ACCOUNT_ID, PROTOCOL_ACCOUNT_ID,
                "ONLINE", "OFFLINE", occurredAt,
                "NORMAL_GROUP_ACCOUNT_NOT_ONLINE", null, "normal_group_creation", null, null);
    }

    private void assertOnlineAt(long occurredAt) {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        assertThat(jdbc.queryForObject(
                "SELECT login_state FROM account_state WHERE account_id = 100",
                Integer.class)).isEqualTo(AccountLoginStateCode.ONLINE);
        assertThat(jdbc.queryForObject(
                "SELECT last_state_sync_time FROM account_state WHERE account_id = 100",
                Long.class)).isEqualTo(occurredAt);
    }

    private void assertNoNormalGroupSideEffects() {
        verify(sideEffect, never()).afterStateChanged(
                org.mockito.ArgumentMatchers.any(Account.class),
                org.mockito.ArgumentMatchers.argThat(event ->
                        "normal_group_creation".equals(event.source())),
                org.mockito.ArgumentMatchers.anyLong());
    }

    private static void await(CountDownLatch latch) {
        try {
            if (!latch.await(2, TimeUnit.SECONDS)) {
                throw new IllegalStateException("等待并发测试信号超时");
            }
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("并发测试被中断", ex);
        }
    }

    private void execute(String sql) throws SQLException {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    @Configuration(proxyBeanMethods = false)
    @EnableTransactionManagement
    @Import(MyBatisConfig.class)
    static class TestConfig {

        @Bean
        DataSource dataSource() {
            JdbcDataSource h2 = new JdbcDataSource();
            h2.setURL("jdbc:h2:mem:account_state_event_concurrency_test;MODE=MySQL;"
                    + "DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=5000");
            h2.setUser("sa");
            h2.setPassword("");
            return h2;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(
                DataSource dataSource,
                MybatisPlusInterceptor interceptor) throws Exception {
            MybatisConfiguration configuration = new MybatisConfiguration();
            configuration.setMapUnderscoreToCamelCase(true);
            MybatisSqlSessionFactoryBean factory = new MybatisSqlSessionFactoryBean();
            factory.setDataSource(dataSource);
            factory.setConfiguration(configuration);
            factory.setPlugins(interceptor);
            factory.setMapperLocations(new ClassPathResource("mapper/account/AccountStateMapper.xml"),
                    new ClassPathResource("mapper/account/AccountOnlineAttemptLogMapper.xml"));
            return factory.getObject();
        }

        @Bean
        SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory factory) {
            return new SqlSessionTemplate(factory);
        }

        @Bean
        AccountStateMapper stateMapper(SqlSessionTemplate template) {
            return template.getMapper(AccountStateMapper.class);
        }

        @Bean
        AccountOnlineAttemptLogService attemptLogService(SqlSessionTemplate template) {
            return new AccountOnlineAttemptLogServiceImpl(template.getMapper(AccountOnlineAttemptLogMapper.class));
        }

        @Bean
        AccountMapper accountMapper() {
            return Mockito.mock(AccountMapper.class);
        }

        @Bean
        IpProxyService ipProxyService() {
            return Mockito.mock(IpProxyService.class);
        }

        @Bean
        AccountStateChangedSideEffect accountStateChangedSideEffect() {
            return Mockito.mock(AccountStateChangedSideEffect.class);
        }

        @Bean
        AccountStateEventService accountStateEventService(
                AccountMapper accountMapper,
                AccountStateMapper stateMapper,
                IpProxyService ipProxyService,
                AccountStateChangedSideEffect sideEffect,
                AccountOnlineAttemptLogService attemptLogService) {
            return new AccountStateEventServiceImpl(
                    accountMapper, stateMapper, ipProxyService,
                    List.of(sideEffect, new ProxyFailureContextSideEffect(attemptLogService)));
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }
    }
}
